Repository Team-inglo/Giggle-Web, pull requests merged in 2024-08, with the labels that each got.

#2 Feature/1-home 홈페이지 레이아웃 개발
  package.json
  pnpm-lock.yaml
  src/App.css
  src/App.tsx
  src/assets/icons/calendar_icon.svg
  src/assets/icons/chat_icon.svg
  src/assets/icons/chatbot_icon.svg
  src/assets/icons/document_icon.svg
  src/assets/icons/hidden_icon.svg
  src/assets/icons/home_icon.svg
  src/assets/icons/map_pin_icon.svg
  src/assets/icons/notice_icon.svg
  src/assets/icons/setting_icon.svg
  src/assets/icons/user_icon.svg
  src/assets/images/chatbot_tooltip.svg
  src/components/Common/Menu/Menu.tsx
  src/components/Common/Menu/styled.ts
  src/components/Main/FloatBtn/MainFloatBtn.tsx
  src/components/Main/FloatBtn/styled.ts
  src/components/Main/Header/MainHeader.tsx
  src/components/Main/Header/style.ts
  src/components/Main/ScoreList/MainScoreList.tsx
  src/components/Main/ScoreList/style.ts
  src/components/Main/UserInfo/MainUserInfo.tsx
  src/components/Main/UserInfo/styled.ts
  src/components/Main/VisaInfo/MainVisaInfo.tsx
  src/components/Main/VisaInfo/style.ts
  src/index.css
  src/main.tsx
  src/pages/Main/MainPage.tsx
  src/pages/Main/style.ts
  src/router.tsx
  src/styles/GlobalStyle.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
  src/svg.d.ts
  src/vite-env.d.ts
  tsconfig.json
  vite.config.ts
Labels: enhancement, 나경

#6 feat: Webview용 거주지 선정 지도 UI 구현
  .gitignore
  index.html
  package.json
  pnpm-lock.yaml
  src/assets/icons/Search.svg
  src/assets/icons/X.svg
  src/components/Common/Menu/MainLayout.tsx
  src/pages/Map/MapPage.tsx
  src/router.tsx
  tsconfig.json
Labels: enhancement

#8 fix #7 - vercel 설정
  vercel.json
Labels: bug

#9 Feature/3-calendar
  package.json
  pnpm-lock.yaml
  src/assets/icons/back_icon.svg
  src/assets/icons/black_calendar_icon.svg
  src/assets/icons/cancel_icon.svg
  src/assets/icons/circle_pencil_icon.svg
  src/assets/icons/delete_icon.svg
  src/assets/icons/menu_icon.svg
  src/assets/images/palette_image.png
  src/components/Common/BackBtnHeader/BackBtnHeader.tsx
  src/components/Common/BackBtnHeader/style.ts
  src/components/Common/Header/MainHeader.tsx
  src/components/Common/Header/style.ts
  src/components/Common/ModalLayout/ModalLayout.tsx
  src/components/Common/ModalLayout/style.ts
  src/components/ScheduleAdd/Calendar/ScheduleAddCalendar.tsx
  src/components/ScheduleAdd/Calendar/style.ts
  src/components/ScheduleAdd/DropDown/ScheduleAddDropDown.tsx
  src/components/ScheduleAdd/DropDown/style.ts
  src/components/ScheduleAdd/Input/ScheduleAddInput.tsx
  src/components/ScheduleAdd/Input/style.ts
  src/components/ScheduleAdd/JobModal/ScheduleAddJobModal.tsx
  src/components/ScheduleAdd/JobModal/style.ts
  src/components/ScheduleEdit/Input/ScheduleEditInput.tsx
  src/components/ScheduleEdit/Input/style.ts
  src/components/ScheduleList/BottomSheet/ScheduleListBottomSheet.tsx
  src/components/ScheduleList/BottomSheet/style.ts
  src/components/ScheduleList/Calendar/ScheduleListCalendar.tsx
  src/components/ScheduleList/Calendar/style.ts
  src/components/ScheduleList/Detail/ScheduleListDetail.tsx
  src/components/ScheduleList/Detail/style.ts
  src/components/ScheduleList/Salary/ScheduleListSalary.tsx
  src/components/ScheduleList/Salary/style.ts
  src/components/ScheduleList/job/ScheduleListJob.tsx
  src/components/ScheduleList/job/style.ts
  src/constants/bottomSheet.ts
  src/hooks/useBottomSheet.ts
  src/hooks/usePreviousValue.ts
  src/interfaces/Schedule/JobSchedule.ts
  src/pages/Main/MainPage.tsx
  src/pages/Main/style.ts
  src/pages/ScheduleAdd/ScheduleAddPage.tsx
  src/pages/ScheduleAdd/style.ts
  src/pages/ScheduleEdit/ScheduleEditPage.tsx
  src/pages/ScheduleEdit/style.ts
  src/pages/ScheduleList/ScheduleListPage.tsx
  src/pages/ScheduleList/style.ts
  src/router.tsx
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
Labels: enhancement, 나경

#11 Feature/10 home
  src/assets/icons/file_icon.svg
  src/assets/icons/logout_icon.svg
  src/assets/icons/notice_icon.svg
  src/assets/icons/question_icon.svg
  src/assets/icons/user_info_icon.svg
  src/components/Common/Header/MainHeader.tsx
  src/components/Common/Header/style.ts
  src/components/Common/Menu/Menu.tsx
  src/components/Common/Menu/styled.ts
  src/pages/Setting/SettingPage.tsx
  src/pages/Setting/style.ts
  src/router.tsx
Labels: enhancement, 나경

#13 Feature/12 notice
  src/assets/icons/dropdown_icon.svg
  src/assets/icons/info_icon.svg
  src/assets/icons/like_icon.svg
  src/assets/icons/region_arrow_icon.svg
  src/components/JobDetail/Button/JobDetailButton.tsx
  src/components/JobDetail/Button/style.ts
  src/components/JobDetail/Info/JobDetailInfo.tsx
  src/components/JobDetail/Info/style.ts
  src/components/JobList/BottomSheet/JobListBottomSheet.tsx
  src/components/JobList/BottomSheet/style.ts
  src/components/JobList/Category/JobListCategory.tsx
  src/components/JobList/Category/style.ts
  src/components/JobList/Filter/JobLIstFilter.tsx
  src/components/JobList/Filter/style.ts
  src/components/JobList/Notice/JobListNotice.tsx
  src/components/JobList/Notice/style.ts
  src/components/JobList/Region/JobListRegion.tsx
  src/components/JobList/Region/style.ts
  src/constants/jobCategory.ts
  src/constants/jobSearchFilter.ts
  src/hooks/useBottomSheet.ts
  src/pages/JobDetail/JobDetailPage.tsx
  src/pages/JobDetail/style.ts
  src/pages/JobList/JobListPage.tsx
  src/pages/JobList/style.ts
  src/pages/Setting/style.ts
  src/router.tsx
  src/styles/theme.ts
Labels: enhancement, 나경

#15 ✨Feat: 챗봇 페이지 레이아웃 구현
  src/assets/icons/gigi_icon.svg
  src/assets/icons/send_icon.svg
  src/pages/ChatBot/ChatBotPage.tsx
  src/pages/ChatBot/style.ts
  src/router.tsx
Labels: enhancement, 나경

#17 [Feature] - 캘린더 메뉴 로직 구현하기
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/JobDetail/Button/JobDetailButton.tsx
  src/components/JobList/Notice/JobListNotice.tsx
  src/components/ScheduleAdd/Calendar/ScheduleAddCalendar.tsx
  src/components/ScheduleAdd/Calendar/ScheduleAddCalendarDays.tsx
  src/components/ScheduleAdd/Calendar/style.ts
  src/components/ScheduleAdd/DropDown/ScheduleAddDropDown.tsx
  src/components/ScheduleAdd/Input/ScheduleAddInput.tsx
  src/components/ScheduleAdd/Input/style.ts
  src/components/ScheduleAdd/JobModal/ScheduleAddJobCreateModal.tsx
  src/components/ScheduleAdd/JobModal/ScheduleAddJobEditModal.tsx
  src/components/ScheduleAdd/JobModal/ScheduleAddJobModal.tsx
  src/components/ScheduleEdit/Input/ScheduleEditInput.tsx
  src/components/ScheduleEdit/Input/style.ts
  src/components/ScheduleList/BottomSheet/ScheduleListBottomSheet.tsx
  src/components/ScheduleList/Calendar/ScheduleListCalendar.tsx
  src/components/ScheduleList/Detail/ScheduleListDetail.tsx
  src/components/ScheduleList/Detail/style.ts
  src/components/ScheduleList/Salary/ScheduleListSalary.tsx
  src/components/ScheduleList/job/ScheduleListJob.tsx
  src/constants/queryKey.ts
  src/hooks/services/calendar/mutations.ts
  src/hooks/services/calendar/queries.ts
  src/hooks/services/home/queries.ts
  src/interfaces/Schedule/JobSchedule.ts
  src/interfaces/calendar/partTime.ts
  src/interfaces/calendar/totalSchedule.ts
  src/interfaces/common/apiResponse.ts
  src/pages/Main/style.ts
  src/pages/ScheduleEdit/ScheduleEditPage.tsx
  src/pages/ScheduleEdit/style.ts
  src/router.tsx
  src/styles/theme.ts
  src/utils/dateTimeUtil.ts
Labels: enhancement, 나경

#22 공고 등록 UI 구현
  src/components/EmployerRegistration/CompleteModal.tsx
  src/components/EmployerRegistration/EmployerRegistrationFourth.tsx
  src/components/EmployerRegistration/EmployerRegistrationInput.tsx
  src/components/EmployerRegistration/EmployerRegistrationSecond.tsx
  src/components/EmployerRegistration/EmployerRegistrationThird.tsx
  src/components/EmployerRegistration/PageConnector.tsx
  src/components/EmployerRegistration/style.ts
  src/components/EmployerRegistration/types.ts
  src/components/EmployerRegistration/utils.ts
  src/pages/EmployerRegistration/EmployerRegistrationPage.tsx
  src/pages/EmployerRegistration/style.ts
  src/pages/Map/MapPage.tsx
  src/router.tsx
Labels: enhancement

#25 [Feature] - 고용주 버전 서류 페이지 작업 및 api 연결하기
  src/components/Common/EmployerHeader/EmployerHeader.tsx
  src/components/Common/EmployerHeader/style.ts
  src/components/Common/MainHeader/MainHeader.tsx
  src/components/Common/MainHeader/style.ts
  src/components/Common/ScrollToTop/ScrollToTop.tsx
  src/components/EmployerDocument/Notice/EmployerDocumentNotice.tsx
  src/components/EmployerDocument/Notice/style.ts
  src/components/EmployerDocument/Tab/EmployerDocumentTab.tsx
  src/components/EmployerDocument/Tab/style.ts
  src/components/EmployerDocumentDetail/Applicant/EmployerDocumentDetailApplicant.tsx
  src/components/EmployerDocumentDetail/Applicant/style.ts
  src/components/EmployerDocumentDetail/JobInfo/EmployerDocumentDetailJobInfo.tsx
  src/components/EmployerDocumentDetail/JobInfo/style.ts
  src/components/EmployerJobList/BottomSheet/EmployerJobListBottomSheet.tsx
  src/components/JobDetail/Info/JobDetailInfo.tsx
  src/components/JobList/BottomSheet/JobListBottomSheet.tsx
  src/components/JobList/Category/JobListCategory.tsx
  src/components/JobList/Notice/JobListNotice.tsx
  src/components/Main/ScoreList/MainScoreList.tsx
  src/components/Main/UserInfo/MainUserInfo.tsx
  src/components/Main/VisaInfo/MainVisaInfo.tsx
  src/components/ScheduleAdd/Calendar/ScheduleAddCalendar.tsx
  src/components/ScheduleAdd/Calendar/ScheduleAddCalendarDays.tsx
  src/components/ScheduleAdd/Calendar/style.ts
  src/components/ScheduleAdd/DropDown/ScheduleAddDropDown.tsx
  src/components/ScheduleAdd/Input/ScheduleAddInput.tsx
  src/components/ScheduleAdd/JobModal/ScheduleAddJobCreateModal.tsx
  src/components/ScheduleList/Salary/ScheduleListSalary.tsx
  src/constants/jobSearchFilter.ts
  src/constants/koreaRegion.ts
  src/constants/queryKey.ts
  src/hooks/services/calendar/mutations.ts
  src/hooks/services/calendar/queries.ts
  src/hooks/services/chatbot/mutations.ts
  src/hooks/services/home/queries.ts
  src/hooks/services/notice/queries.ts
  src/interfaces/calendar/partTime.ts
  src/interfaces/document/applicantStatus.ts
  src/interfaces/document/employerNotice.ts
  src/interfaces/home/homeInfo.ts
  src/interfaces/notice/jobNotice.ts
  src/interfaces/notice/jobNoticeDetail.ts
  src/interfaces/notice/noticeListFilter.ts
  src/pages/ChatBot/ChatBotPage.tsx
  src/pages/ChatBot/style.ts
  src/pages/EmployerDocument/EmployerDocumentPage.tsx
  src/pages/EmployerDocument/style.ts
  src/pages/EmployerDocumentDetail/EmployerDocumentDetail.tsx
  src/pages/EmployerDocumentDetail/style.ts
  src/pages/EmployerJobList/EmployerJobList.tsx
  src/pages/JobList/JobListPage.tsx
  src/pages/Main/MainPage.tsx
  src/pages/ScheduleList/ScheduleListPage.tsx
  src/router.tsx
Labels: enhancement, 나경
