Repository Team-inglo/Giggle-Web, pull requests merged in 2024-10, with the labels that each got.

#2 [Feat/igw-17/1] - 프로젝트 세팅하기
  .eslintrc.cjs
  .github/ISSUE_TEMPLATE/-feature----작업할-것.md
  .github/ISSUE_TEMPLATE/-fix-----작업할-것.md
  .github/pull_request_template.md
  .github/workflows/deploy.yml
  .gitignore
  .prettierignore
  .prettierrc
  README.md
  build.sh
  eslint.config.js
  index.html
  package.json
  pnpm-lock.yaml
  postcss.config.js
  public/vite.svg
  src/App.tsx
  src/api/auth.ts
  src/api/index.ts
  src/assets/icons/.gitkeep
  src/assets/images/.gitkeep
  src/components/Common/.gitkeep
  src/hooks/.gitkeep
  src/hooks/api/useAuth.ts
  src/index.css
  src/main.tsx
  src/pages/Home/HomePage.tsx
  src/router.tsx
  src/svg.d.ts
  src/types/api/auth.ts
  src/types/common/.gitkeep
  src/utils/.gitkeep
  src/utils/auth.ts
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: ✨ Feature, ⚙️ Setting

#4 Feat/IGW-18/3-field 공용 컴포넌트 작성
  package.json
  pnpm-lock.yaml
  src/assets/icons/ArrowUp.tsx
  src/assets/icons/CloseIcon.svg
  src/assets/icons/Hide.svg
  src/assets/icons/MagnifyGlassIcon.svg
  src/components/Common/DatePicker.tsx
  src/components/Common/Dropdown.tsx
  src/components/Common/Input.tsx
  src/pages/Test/TestPage.tsx
  src/style/CustomCalendar.module.css
Labels: ✨ Feature, 🎨 Html&CSS

#6 Feat/igw 19/5 information
  .gitignore
  package.json
  pnpm-lock.yaml
  src/assets/icons/Chevron.svg
  src/assets/icons/ChevronLeft.svg
  src/assets/icons/btn_radio_off.svg
  src/assets/icons/btn_radio_on.svg
  src/components/Common/DatePicker.tsx
  src/components/Common/Dropdown.tsx
  src/components/Common/Input.tsx
  src/components/Information/InformationStep.tsx
  src/components/Information/RadioButton.tsx
  src/components/Information/StepIndicator.tsx
  src/constants/information.ts
  src/pages/Information/InformationPage.tsx
  src/router.tsx
  src/types/api/users.ts
  src/types/common/input.ts
  src/utils/information.ts
  tailwind.config.js
Labels: ✨ Feature, 🎨 Html&CSS

#7 [Feat/igw-18/3-tag] - 폰트 적용 및 Tag 컴포넌트 개발
  pnpm-lock.yaml
  src/assets/fonts/PretendardVariable.woff2
  src/assets/icons/TagCheckIcon.tsx
  src/assets/icons/TagDeleteIcon.tsx
  src/components/Common/Tag.tsx
  src/index.css
  tailwind.config.js
Labels: ✨ Feature, 🎨 Html&CSS

#8 [Feat/igw-18/3-header] - header 컴포넌트 제작하기
  src/assets/icons/BackButtonIcon.svg
  src/assets/icons/CircleDeleteIcon.svg
  src/assets/icons/ColumnMenuIcon.svg
  src/assets/icons/FilterIcon.svg
  src/assets/icons/LikeIcon.svg
  src/assets/icons/RowMenuIcon.svg
  src/assets/icons/SearchIcon.svg
  src/assets/icons/ShareIcon.svg
  src/components/Common/Header/ActionHeader.tsx
  src/components/Common/Header/BaseHeader.tsx
  src/components/Common/Header/TextFieldHeader.tsx
Labels: ✨ Feature, 🎨 Html&CSS

#11 Fix/igw 21/10
  .gitignore
  src/components/Common/DatePicker.tsx
  src/pages/Test/TestPage.tsx
Labels: 🐞 BugFix, 📄 Docs

#12 Feat/IGW-18/3-navbar 네브바 컴포넌트 작성
  pnpm-lock.yaml
  src/assets/icons/.gitkeep
  src/assets/icons/DocumentsIcon.svg
  src/assets/icons/HomeIcon.svg
  src/assets/icons/NavSearchIcon.svg
  src/assets/icons/ProfileIcon.svg
  src/components/Common/.gitkeep
  src/components/Common/Navbar.tsx
  tailwind.config.js
Labels: ✨ Feature, 🎨 Html&CSS

#13 Feat/IGW-18/3-button 버튼 컴포넌트 작성
  src/assets/icons/CallIcon.svg
  src/assets/images/.gitkeep
  src/assets/images/applyButton.jpeg
  src/components/Common/Button.tsx
  src/constants/components.ts
  tailwind.config.js
Labels: ✨ Feature, 🎨 Html&CSS

#14 [Feat/IGW-20/9] Home 페이지 퍼블리싱하기
  src/assets/icons/BookmarkCheckedIcon.svg
  src/assets/icons/BookmarkIcon.svg
  src/assets/icons/CalendarIcon.svg
  src/assets/icons/ClockIcon.svg
  src/assets/icons/Home/AlarmIcon.svg
  src/assets/icons/Home/MessageIcon.svg
  src/assets/icons/Home/RightArrowIcon.svg
  src/assets/icons/Home/TopRightArrowIcon.svg
  src/assets/icons/LocationIcon.svg
  src/assets/images/JobIconExample.jpeg
  src/components/Common/JobPostingCard.tsx
  src/components/Common/Tag.tsx
  src/components/Home/HomeApplicationCard.tsx
  src/components/Home/HomeApplicationList.tsx
  src/components/Home/HomeGuestBanner.tsx
  src/components/Home/HomeHeader.tsx
  src/components/Home/HomeJobPostingList.tsx
  src/components/Home/HomeRecommendPost.tsx
  src/components/Home/HomeRecommendPostCard.tsx
  src/index.css
  src/pages/Home/HomePage.tsx
  src/types/common/jobPostingItem.ts
  src/types/home/ongoingInterviewItem.ts
  src/types/home/recommendJobPostingItem.ts
  src/utils/calculateDDay.ts
  src/utils/calculateTimeAgo.ts
  tailwind.config.js
Labels: ✨ Feature, 🎨 Html&CSS

#20 🐛 fix: 빌드 시에 pnpm-lock.yaml 오류 해결하기 #19
  pnpm-lock.yaml
Labels: 🐞 BugFix, 🌏 Deploy

#16 Feat/igw 19/5 information - 주소 입력 step
  index.html
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/api/index.ts
  src/api/map.ts
  src/components/Common/BottomButtonPanel.tsx
  src/components/Common/Dropdown.tsx
  src/components/Information/AddressStep.tsx
  src/components/Information/InformationStep.tsx
  src/components/Information/StepIndicator.tsx
  src/hooks/api/useKaKaoMap.tsx
  src/pages/Information/InformationPage.tsx
  src/types/api/map.ts
  src/types/api/users.ts
  src/utils/map.ts
  tsconfig.json
Labels: ✨ Feature, 🎨 Html&CSS, 📭 API

#18 Feat/IGW-18/3-subHeader 서브헤더 컴포넌트 작성
  src/assets/icons/MoreInfoIcon.svg
  src/assets/icons/SubHeaderSearchIcon.svg
  src/components/Common/SubHeader.tsx
  src/constants/components.ts
Labels: ✨ Feature, 🎨 Html&CSS

#23 Feat/igw 19/5 information - 언어 선택 및 완료 표시 후 페이지 이동
  src/api/auth.ts
  src/assets/icons/checkIconLarge.svg
  src/components/Common/BottomButtonPanel.tsx
  src/components/Common/CompleteModal.tsx
  src/components/Common/DatePicker.tsx
  src/components/Common/Dropdown.tsx
  src/components/Common/Input.tsx
  src/components/Information/AddressStep.tsx
  src/components/Information/InformationStep.tsx
  src/components/Information/LanguageStep.tsx
  src/components/Information/RadioButton.tsx
  src/components/Information/StepIndicator.tsx
  src/constants/information.ts
  src/hooks/api/useAuth.ts
  src/pages/Information/InformationPage.tsx
  src/types/api/auth.ts
  src/types/api/users.ts
Labels: ✨ Feature, 🎨 Html&CSS, 📭 API

#25 Feat/igw 25/24 - 서류 관리 메인 페이지 퍼블리싱
  src/assets/icons/AddButton.svg
  src/assets/icons/CheckIconGreen.svg
  src/assets/icons/DownloadIcon.svg
  src/assets/icons/FolderIcon.svg
  src/assets/icons/TalkBalloon.svg
  src/assets/icons/TalkBalloonGrey.svg
  src/assets/icons/WriteIcon.svg
  src/components/Document/DocumentCard.tsx
  src/components/Document/DocumentCardList.tsx
  src/components/Document/MakeDocumentButton.tsx
  src/constants/documents.ts
  src/pages/ApplicationDocuments/ApplicationDocumentsPage.tsx
  src/router.tsx
  src/types/api/document.ts
Labels: ✨ Feature, 🎨 Html&CSS

#29 [Feat/igw-22/15] BottomSheet 컴포넌트 만들기, 공고 검색 페이지 구현하기, Header 컴포넌트 오류 수정하기
  package.json
  pnpm-lock.yaml
  src/assets/icons/LeftArrowIcon.svg
  src/assets/icons/PostSearch/DownArrowIcon.svg
  src/assets/images/NoSearchResultImg.png
  src/components/Common/BottomSheetLayout.tsx
  src/components/Common/Header/BaseHeader.tsx
  src/components/Common/Header/TextFieldHeader.tsx
  src/components/Common/Tag.tsx
  src/components/PostSearch/PostSearchFilterList.tsx
  src/components/PostSearch/PostSearchResult.tsx
  src/components/PostSearch/PostSearchSortDropdown.tsx
  src/components/PostSearchFilter/PostSearchFilterArea.tsx
  src/components/PostSearchFilter/PostSearchFilterAreaInput.tsx
  src/components/PostSearchFilter/PostSearchFilterAreaSelect.tsx
  src/components/PostSearchFilter/PostSearchFilterBottomSheet.tsx
  src/components/PostSearchFilter/PostSearchFilterButtons.tsx
  src/components/PostSearchFilter/PostSearchFilterList.tsx
  src/components/PostSearchFilter/PostSearchFilterToggle.tsx
  src/constants/postSearch.ts
  src/hooks/useBottomSheet.ts
  src/hooks/usePreviousValue.ts
  src/pages/PostSearch/PostSearchPage.tsx
  src/pages/PostSearchFilter/PostSearchFilterPage.tsx
  src/router.tsx
  src/types/PostSearchFilter/PostSearchFilterItem.ts
  tailwind.config.js
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&CSS

#27 Feat/IGW-23/17. Onboarding, Sign in, Sign up 페이지 작업
  src/assets/icons/Apple.svg
  src/assets/icons/DividerLine.svg
  src/assets/icons/Facebook.svg
  src/assets/icons/GiggleSplash.svg
  src/assets/icons/Google.svg
  src/assets/icons/SignupStroke.svg
  src/assets/icons/Splash.svg
  src/assets/icons/Successful.svg
  src/assets/images/journeyCard.png
  src/assets/images/ownerCard.png
  src/components/Common/Button.tsx
  src/components/Common/SubHeader.tsx
  src/components/Signin/SigninInputSection.tsx
  src/components/Signin/SigninSocialButtons.tsx
  src/components/Signup/EmailInput.tsx
  src/components/Signup/FindJourney.tsx
  src/components/Signup/SignupInput.tsx
  src/components/Signup/SignupVerification.tsx
  src/components/Signup/VerificationSuccessful.tsx
  src/components/Splash/GiggleSplash.tsx
  src/components/Splash/Splash.tsx
  src/constants/user.ts
  src/pages/Signin/SigninPage.tsx
  src/pages/Signup/SignupPage.tsx
  src/router.tsx
  src/utils/signin.ts
  tailwind.config.js
Labels: ✨ Feature, 🎨 Html&CSS

#32 Feat/IGW-27/28 - 마이페이지, 언어설정 페이지 작업
  src/assets/icons/Profile/LanguageIcon.svg
  src/assets/icons/Profile/LevelIcon.svg
  src/assets/icons/Profile/LogoutIcon.svg
  src/assets/icons/Profile/ManageIcon.svg
  src/assets/icons/Profile/NotificationIcon.svg
  src/assets/icons/Profile/ProfileIcon.svg
  src/assets/icons/Profile/ScrappedIcon.svg
  src/assets/icons/Profile/ToggleBar.svg
  src/assets/icons/Profile/ToggleButton.svg
  src/assets/icons/Scrap.svg
  src/components/Common/Button.tsx
  src/components/Common/SubHeader.tsx
  src/components/Profile/ApplicationStatus.tsx
  src/components/Profile/DeleteAccount.tsx
  src/components/Profile/DeleteModal.tsx
  src/components/Profile/EditProfilePicture.tsx
  src/components/Profile/LevelSection.tsx
  src/components/Profile/LicenseCard.tsx
  src/components/Profile/ProfileCard.tsx
  src/components/Profile/ProfileHeader.tsx
  src/components/Profile/ProfileMenu.tsx
  src/components/Profile/ProfileMenuList.tsx
  src/constants/components.ts
  src/constants/profile.ts
  src/pages/Profile/EditProfilePage.tsx
  src/pages/Profile/LanguageSettingPage.tsx
  src/pages/Profile/ProfilePage.tsx
  src/router.tsx
  src/types/api/profile.ts
  tailwind.config.js
Labels: ✨ Feature, 🎨 Html&CSS

#33 [Feat/igw-28/30] 공고 상세 페이지 구현하기
  src/assets/icons/CloseWhiteIcon.svg
  src/assets/icons/MoneyIcon.svg
  src/assets/icons/PersonIcon.svg
  src/assets/icons/SmallCheckIcon.svg
  src/components/Common/BottomSheetLayout.tsx
  src/components/Common/CompleteButtonModal.tsx
  src/components/Common/JobPostingCard.tsx
  src/components/Common/ScrollToTop.tsx
  src/components/PostApply/PostApplyButton.tsx
  src/components/PostApply/PostApplyCardLayout.tsx
  src/components/PostApply/PostApplyProfile.tsx
  src/components/PostApply/PostApplyResume.tsx
  src/components/PostApply/PostApplyTitle.tsx
  src/components/PostDetail/PostDetailApplyButton.tsx
  src/components/PostDetail/PostDetailCompanyImageList.tsx
  src/components/PostDetail/PostDetailConfirmBottomSheet.tsx
  src/components/PostDetail/PostDetailContent.tsx
  src/components/PostDetail/PostDetailContentMenuBar.tsx
  src/components/PostDetail/PostDetailLoginBottomSheet.tsx
  src/components/PostDetail/PostDetailTitle.tsx
  src/constants/postDetail.ts
  src/hooks/useBottomSheet.ts
  src/pages/PostApply/PostApplyPage.tsx
  src/pages/PostDetail/PostDetailPage.tsx
  src/router.tsx
  src/types/postApply/resumeDetailItem.ts
  src/types/postDetail/postDetailItem.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&CSS

#35 Feat/igw 29/31
  pnpm-lock.yaml
  src/api/auth.ts
  src/api/document.ts
  src/components/Common/BottomButtonPanel.tsx
  src/components/Common/Dropdown.tsx
  src/components/Document/DocumentCardList.tsx
  src/components/Document/MakeDocumentButton.tsx
  src/components/Document/write/DocumentSubHeader.tsx
  src/components/Document/write/EmployerInfoSection.tsx
  src/components/Information/AddressStep.tsx
  src/components/Information/InformationStep.tsx
  src/components/Information/LanguageStep.tsx
  src/components/WriteDocuments/DocumentFormDispenser.tsx
  src/components/WriteDocuments/IntegratedApplicationWriteForm.tsx
  src/components/WriteDocuments/LaborContractWriteForm.tsx
  src/components/WriteDocuments/PartTimePermitWriteForm.tsx
  src/constants/documents.ts
  src/hooks/api/useDocument.ts
  src/pages/ApplicationDocuments/ApplicationDocumentsPage.tsx
  src/pages/Information/InformationPage.tsx
  src/pages/WriteDocuments/WriteDocumentsPage.tsx
  src/router.tsx
  src/types/api/auth.ts
  src/types/api/document.ts
  src/utils/document.ts
Labels: ✨ Feature, 🎨 Html&CSS, 📭 API

#37 Feat/igw 27/28 - 프로필 수정 페이지 작업
  src/components/Profile/EditProfilePicture.tsx
  src/components/Profile/ProfileCard.tsx
  src/constants/profile.ts
  src/pages/Profile/EditProfilePage.tsx
  src/pages/Profile/ProfilePage.tsx
  src/types/api/profile.ts
  src/utils/editProfileData.ts
Labels: ✨ Feature, 🎨 Html&CSS

#40 Fix/igw-32/39 - nav bar 조건부 랜더링 및 스타일 변경
  src/components/Common/Navbar.tsx
  src/components/Profile/DeleteAccount.tsx
  src/router.tsx
Labels: 🎨 Html&CSS

#45 [Feat/igw-33/41] - 서류 지원 상태 상세 조회 구현하기
  pnpm-lock.yaml
  src/assets/icons/ApplicationDetail/CheckStepIcon.svg
  src/assets/icons/ApplicationDetail/CurrentStepIcon.svg
  src/assets/icons/ApplicationDetail/SmallCheckGrayIcon.svg
  src/assets/icons/ApplicationDetail/UncheckStepIcon.svg
  src/assets/icons/PhoneIcon.svg
  src/assets/images/blueGradient.png
  src/assets/images/yellowGradient.png
  src/components/Application/ApplicationCard.tsx
  src/components/ApplicationDetail/ApplicationDetailBottomSheet.tsx
  src/components/ApplicationDetail/ApplicationDetailCard.tsx
  src/components/ApplicationDetail/ApplicationDetailInfo.tsx
  src/components/ApplicationDetail/ApplicationDetailStep1.tsx
  src/components/ApplicationDetail/ApplicationDetailStep2.tsx
  src/components/ApplicationDetail/ApplicationDetailStep3.tsx
  src/components/ApplicationDetail/ApplicationDetailStep4.tsx
  src/components/ApplicationDetail/ApplicationDetailStep5.tsx
  src/components/ApplicationDetail/ApplicationDetailStep6.tsx
  src/components/ApplicationDetail/ApplicationDetailStep7.tsx
  src/components/ApplicationDetail/ApplicationDetailStepBarLayout.tsx
  src/components/ApplicationDetail/ApplicationDetailStepEtc.tsx
  src/components/ApplicationDetail/ApplicationDetailSteps.tsx
  src/components/ApplicationDetail/ContactCoordinatorModal.tsx
  src/components/ApplicationDetail/ContactRecruiterModal.tsx
  src/components/Common/JobPostingCard.tsx
  src/components/Home/HomeGuestBanner.tsx
  src/components/Home/HomeRecommendPost.tsx
  src/components/Home/HomeRecommendPostCard.tsx
  src/pages/ApplicationDetail/ApplicationDetailPage.tsx
  src/pages/ApplicationResult/ApplicationResultPage.tsx
  src/router.tsx
  src/types/application/applicationItem.ts
  src/types/postDetail/postDetailItem.ts
  src/utils/application.ts
Labels: ✨ Feature, 🎨 Html&CSS

#47 [feat/IGW-36/46] zustand 세팅해서 공고 검색 필터 저장하기
  package.json
  pnpm-lock.yaml
  src/components/Common/Header/TextFieldHeader.tsx
  src/components/PostSearch/PostSearchFilterList.tsx
  src/components/PostSearchFilter/PostSearchFilterButtons.tsx
  src/constants/postSearch.ts
  src/pages/PostSearch/PostSearchPage.tsx
  src/pages/PostSearchFilter/PostSearchFilterPage.tsx
  src/store/postSearch.ts
Labels: ✨ Feature, 🎨 Html&CSS, ⚙️ Setting

#52 Feat/igw 35/44/통합신청서
  pnpm-lock.yaml
  src/api/document.ts
  src/assets/icons/Common/calendar/Chevron_bold_left.svg
  src/assets/icons/Common/calendar/Chevron_light_left.svg
  src/assets/icons/Common/calendar/Chevron_light_right.svg
  src/components/Common/DatePicker.tsx
  src/components/Document/write/InputLayout.tsx
  src/components/Document/write/Notice.tsx
  src/components/Document/write/SearchSchoolBottomSheet.tsx
  src/components/WriteDocuments/IntegratedApplicationWriteForm.tsx
  src/constants/documents.ts
  src/hooks/api/useDocument.ts
  src/pages/ApplicationDocuments/ApplicationDocumentsPage.tsx
  src/types/api/document.ts
  src/utils/document.ts
Labels: ✨ Feature, 🎨 Html&CSS, 📭 API

#51 Feat/IGW-34/42 - 이력서 관리 페이지, 경력﹒소개 작성 페이지 작업
  src/api/mypage.ts
  src/api/resumes.ts
  src/assets/icons/ManageResume/BigEditIcon.svg
  src/assets/icons/ManageResume/BlackCtaIcon.svg
  src/assets/icons/ManageResume/CtaIcon.svg
  src/assets/icons/ManageResume/DeleteIcon.svg
  src/assets/icons/ManageResume/EditIcon.svg
  src/assets/icons/ManageResume/EducationIcon.svg
  src/assets/icons/ManageResume/LanguageIcon.svg
  src/assets/icons/ManageResume/Profile.svg
  src/assets/icons/ManageResume/WorkIcon.svg
  src/components/Common/Button.tsx
  src/components/Introduction/IntroductionInput.tsx
  src/components/ManageResume/MypageCardSection.tsx
  src/components/ManageResume/ProfilePicture.tsx
  src/components/ManageResume/ResumeEditSection.tsx
  src/components/ManageResume/components/MypageCard.tsx
  src/components/ManageResume/components/ResumeManageBox.tsx
  src/components/Profile/ProfileMenuList.tsx
  src/components/WorkExperience/InputLayout.tsx
  src/components/WorkExperience/WorkExperiencePatch.tsx
  src/components/WorkExperience/WorkExperiencePost.tsx
  src/constants/manageResume.ts
  src/hooks/api/useProfile.ts
  src/hooks/api/useResume.ts
  src/hooks/api/useSetting.ts
  src/hooks/useNavigateBack.ts
  src/pages/Introduction/IntroductionPage.tsx
  src/pages/Language/LanguagePage.tsx
  src/pages/ManageResumePage/ManageResumePage.tsx
  src/pages/Profile/EditProfilePage.tsx
  src/pages/Profile/LanguageSettingPage.tsx
  src/pages/ScrappedJobPosts/ScrappedJobPostsPage.tsx
  src/pages/SetEducation/PatchEducationPage.tsx
  src/pages/SetEducation/PostEducationPage.tsx
  src/pages/SetWorkExperience/PatchWorkExperiencePage.tsx
  src/pages/SetWorkExperience/PostWorkExperiencePage.tsx
  src/router.tsx
  src/types/api/mypage.ts
  src/types/api/resumes.ts
  src/types/manageResume/manageResume.ts
  src/types/postApply/resumeDetailItem.ts
  src/types/postResume/postWorkExperience.ts
  src/utils/editResume.ts
  tailwind.config.js
Labels: ✨ Feature, 🎨 Html&CSS

#53 [Feat/igw-38/50] 고용주 버전 공고 목록 및 지원자 목록 페이지 작업하기
  pnpm-lock.yaml
  src/api/post.ts
  src/components/Application/ApplicationCard.tsx
  src/components/Common/BottomSheetLayout.tsx
  src/components/Common/Header/BaseHeader.tsx
  src/components/Common/SearchSortDropdown.tsx
  src/components/Employer/ApplicantList/EmployerApplicantCard.tsx
  src/components/Employer/ApplicantList/EmployerApplicantList.tsx
  src/components/Employer/ApplicantList/EmployerApplicantListTitle.tsx
  src/components/Employer/Post/EmployerPostCard.tsx
  src/components/Employer/Post/EmployerPostCardList.tsx
  src/constants/application.ts
  src/constants/post.ts
  src/constants/postDetail.ts
  src/constants/sort.ts
  src/hooks/api/usePost.ts
  src/pages/Application/ApplicationPage.tsx
  src/pages/Employer/ApplicantList/EmployerApplicantListPage.tsx
  src/pages/Employer/Post/EmployerPostPage.tsx
  src/router.tsx
  src/types/application/applicationItem.ts
  src/types/application/applicationStatus.ts
  src/types/common/sort.ts
  src/types/post/employerPostItem.ts
  src/types/post/postSummaryItem.ts
  src/types/postDetail/postDetailItem.ts
Labels: ✨ Feature, 🎨 Html&CSS, 📭 API

#56 Feat/igw 34/42 - 학력 생성, 수정 페이지 작업
  src/api/resumes.ts
  src/assets/icons/ManageResume/GraySearchIcon.svg
  src/components/ManageResume/ResumeEditSection.tsx
  src/components/Profile/EditProfilePicture.tsx
  src/components/SetEducation/EducationPatch.tsx
  src/components/SetEducation/EducationPost.tsx
  src/components/SetEducation/SearchSchools.tsx
  src/constants/manageResume.ts
  src/hooks/api/useResume.ts
  src/pages/Introduction/IntroductionPage.tsx
  src/pages/Profile/EditProfilePage.tsx
  src/pages/SetEducation/PatchEducationPage.tsx
  src/pages/SetEducation/PostEducationPage.tsx
  src/pages/SetWorkExperience/PatchWorkExperiencePage.tsx
  src/pages/SetWorkExperience/PostWorkExperiencePage.tsx
  src/pages/Signup/SignupPage.tsx
  src/types/postResume/postEducation.ts
  src/utils/editResume.ts
  src/utils/introduction.ts
Labels: ✨ Feature, 🎨 Html&CSS

#57 Feat/igw 39/54/서류 미리보기/수정/수정요청
  src/api/document.ts
  src/assets/icons/InfoIcon.svg
  src/components/Document/DocumentCard.tsx
  src/components/Document/DocumentCardList.tsx
  src/components/Document/write/EmployeeInfoSection.tsx
  src/components/Document/write/EmployerInfoSection.tsx
  src/components/Document/write/InfoAlert.tsx
  src/components/Document/write/IntegratedApplicationPreview.tsx
  src/components/WriteDocuments/DocumentFormDispenser.tsx
  src/components/WriteDocuments/IntegratedApplicationWriteForm.tsx
  src/components/WriteDocuments/LaborContractWriteForm.tsx
  src/components/WriteDocuments/PartTimePermitWriteForm.tsx
  src/constants/documents.ts
  src/hooks/api/useDocument.ts
  src/pages/ApplicationDocuments/ApplicationDocumentsPage.tsx
  src/pages/WriteDocuments/DocumentPreviewPage.tsx
  src/pages/WriteDocuments/RequestModifyPage.tsx
  src/pages/WriteDocuments/WriteDocumentsPage.tsx
  src/router.tsx
  src/types/api/document.ts
  src/utils/map.ts
  src/utils/map.tsx
Labels: ✨ Feature, 🎨 Html&CSS, 📭 API

#59 [Feat/igw-40/55] 고용주 지원자 상태 페이지 구현하기
  src/api/application.ts
  src/api/post.ts
  src/api/resumes.ts
  src/components/ApplicationDetail/ApplicationDetailStepBarLayout.tsx
  src/components/ApplicationDetail/ApplicationDetailStepEtc.tsx
  src/components/ApplicationDetail/ApplicationDetailSteps.tsx
  src/components/Employer/ApplicantDetail/EmployerApplicantContactBottomSheet.tsx
  src/components/Employer/ApplicantDetail/EmployerApplicantDetailButton.tsx
  src/components/Employer/ApplicantDetail/EmployerApplicantDetailCard.tsx
  src/components/Employer/ApplicantList/EmployerApplicantCard.tsx
  src/components/Employer/ApplicantResumeAccept/EmployerApplicantResumeButton.tsx
  src/constants/application.ts
  src/hooks/api/useApplication.ts
  src/hooks/api/useResume.ts
  src/pages/ApplicationDetail/ApplicationDetailPage.tsx
  src/pages/Employer/ApplicantDetail/EmployerApplicantDetailPage.tsx
  src/pages/Employer/ApplicantResume/EmployerApplicantResumePage.tsx
  src/pages/Employer/ApplicantResumeAccept/EmployerApplicantResumeAcceptPage.tsx
  src/router.tsx
  src/types/api/application.ts
  src/types/application/applicationItem.ts
  src/types/postDetail/postDetailItem.ts
Labels: ✨ Feature, 🎨 Html&CSS, 📭 API

#58 Feat/igw 34/42 - 이력서 언어 설정 페이지 작업
  src/api/mypage.ts
  src/api/resumes.ts
  src/assets/icons/Language/AddIcon.svg
  src/assets/icons/Language/ArrowIcon.svg
  src/assets/icons/Language/EditIcon.svg
  src/assets/icons/Language/TrashcanIcon.svg
  src/assets/images/koreanFlag.png
  src/assets/images/usFlag.png
  src/components/Common/BottomSheetLayout.tsx
  src/components/Language/EtcLanguageCard.tsx
  src/components/Language/EtcLanguageSection.tsx
  src/components/Language/EtcLevelSection.tsx
  src/components/Language/LanguageCard.tsx
  src/components/Language/LanguageSection.tsx
  src/components/Language/LevelBottomSheet.tsx
  src/components/Language/NumberRadioButton.tsx
  src/components/Profile/ProfileMenu.tsx
  src/components/Profile/ProfileMenuList.tsx
  src/constants/language.ts
  src/constants/manageResume.ts
  src/hooks/api/useResume.ts
  src/pages/EditProfile/EditProfilePage.tsx
  src/pages/Language/LanguagePage.tsx
  src/pages/LanguageSetting/LanguageSettingPage.tsx
  src/pages/ManageResumePage/ManageResumePage.tsx
  src/pages/PostLanguage/PostLanguagePage.tsx
  src/pages/Profile/ProfilePage.tsx
  src/pages/ScrappedJobPosts/ScrappedJobPostsPage.tsx
  src/router.tsx
  src/types/api/resumes.ts
  src/types/manageResume/manageResume.ts
  src/types/postApply/resumeDetailItem.ts
Labels: ✨ Feature, 🎨 Html&CSS

#62 [Feat/igw 42/61] 고용주 메인 페이지 구현하기 및 api 정의하기
  src/api/alarm.ts
  src/api/application.ts
  src/api/post.ts
  src/assets/icons/PlusIcon.svg
  src/components/Common/LoginBottomSheet.tsx
  src/components/Employer/ApplicantList/EmployerApplicantList.tsx
  src/components/Home/HomeApplicationCard.tsx
  src/components/Home/HomeEmployerBanner.tsx
  src/components/Home/HomeGuestBanner.tsx
  src/components/Home/HomeJobPostingList.tsx
  src/components/Home/HomeRecommendPost.tsx
  src/components/Home/HomeRecommendPostCard.tsx
  src/components/PostDetail/PostDetailApplyButton.tsx
  src/components/PostSearch/PostSearchResult.tsx
  src/constants/application.ts
  src/constants/postSearch.ts
  src/hooks/api/useAlarm.ts
  src/hooks/api/useApplication.ts
  src/hooks/api/usePost.ts
  src/pages/Application/ApplicationPage.tsx
  src/pages/Home/HomePage.tsx
  src/pages/PostDetail/PostDetailPage.tsx
  src/router.tsx
  src/store/postSearch.ts
  src/types/api/application.ts
  src/types/api/post.ts
Labels: ✨ Feature, 🎨 Html&CSS, 📭 API

#64 [Feat/igw-43/63] 알림 페이지, 채팅 페이지 구현하기
  src/api/alarm.ts
  src/assets/icons/ChatSubmitIcon.svg
  src/assets/icons/YellowLogoIcon.svg
  src/components/Alarm/AlarmCard.tsx
  src/components/ChatBot/ChatBotChatBox.tsx
  src/components/ChatBot/ChatBotInput.tsx
  src/components/ChatBot/UserChatBox.tsx
  src/components/Home/HomeHeader.tsx
  src/constants/alarm.ts
  src/constants/chatbot.ts
  src/hooks/api/useAlarm.ts
  src/pages/Alarm/AlarmPage.tsx
  src/pages/ChatBot/ChatBotPage.tsx
  src/router.tsx
  src/types/api/alarm.ts
  src/types/api/chatbot.ts
  src/utils/getCurrentDateTime.ts
  tailwind.config.js
Labels: ✨ Feature, 🎨 Html&CSS, 📭 API

#74 🐛 fix: 경로 오류로 인해 발생한 빌드 문제 해결 #61
  src/router.tsx
Labels: 🐞 BugFix, 🌏 Deploy

#71 Feat/IGW-47/69 - 고용주 마이페이지 구현
  src/api/mypage.ts
  src/assets/icons/Profile/ToggleBar.svg
  src/assets/icons/Profile/ToggleButton.svg
  src/components/Employer/EditProfile/EmployerEditInputSection.tsx
  src/components/Employer/Profile/EmployerJobInfo.tsx
  src/components/Employer/Profile/EmployerProfileCard.tsx
  src/components/Employer/Profile/EmployerProfileMenuList.tsx
  src/components/Profile/DeleteAccount.tsx
  src/components/Profile/DeleteModal.tsx
  src/components/Profile/LicenseCard.tsx
  src/components/Profile/LogoutBottomSheet.tsx
  src/components/Profile/ProfileCard.tsx
  src/components/Profile/ProfileMenu.tsx
  src/components/Profile/ProfileMenuList.tsx
  src/constants/profile.ts
  src/constants/translation.ts
  src/hooks/api/useProfile.ts
  src/hooks/api/useSetting.ts
  src/pages/EditProfile/EditProfilePage.tsx
  src/pages/Employer/EditProfile/EmployerEditProfilePage.tsx
  src/pages/Employer/Profile/EmployerProfilePage.tsx
  src/pages/Profile/ProfilePage.tsx
  src/router.tsx
  src/types/api/profile.ts
  src/utils/editProfileData.ts
  src/utils/employerProfile.ts
Labels: ✨ Feature, 🎨 Html&CSS, 📭 API

#80 Feat/IGW-49/73 - auth 관련 API 수정 및 프로필 API 연결
  src/api/mypage.ts
  src/api/resumes.ts
  src/assets/images/countryImg/BG.png
  src/assets/images/countryImg/CN.png
  src/assets/images/countryImg/CZ.png
  src/assets/images/countryImg/DE.png
  src/assets/images/countryImg/DK.png
  src/assets/images/countryImg/EE.png
  src/assets/images/countryImg/ES.png
  src/assets/images/countryImg/FI.png
  src/assets/images/countryImg/FR.png
  src/assets/images/countryImg/GB.png
  src/assets/images/countryImg/GR.png
  src/assets/images/countryImg/HU.png
  src/assets/images/countryImg/ID.png
  src/assets/images/countryImg/IT.png
  src/assets/images/countryImg/JP.png
  src/assets/images/countryImg/KR.png
  src/assets/images/countryImg/LT.png
  src/assets/images/countryImg/LV.png
  src/assets/images/countryImg/NL.png
  src/assets/images/countryImg/NO.png
  src/assets/images/countryImg/PL.png
  src/assets/images/countryImg/PT.png
  src/assets/images/countryImg/RO.png
  src/assets/images/countryImg/RU.png
  src/assets/images/countryImg/SA.png
  src/assets/images/countryImg/SE.png
  src/assets/images/countryImg/SI.png
  src/assets/images/countryImg/SK.png
  src/assets/images/countryImg/TR.png
  src/assets/images/countryImg/UA.png
  src/components/Language/EtcLanguageCard.tsx
  src/components/Profile/ApplicationStatus.tsx
  src/components/Profile/LicenseCard.tsx
  src/components/Profile/ProfileCard.tsx
  src/components/Profile/ProfileMenu.tsx
  src/components/Signup/VerificationSuccessful.tsx
  src/components/Splash/Splash.tsx
  src/constants/language.ts
  src/constants/language_data.ts
  src/hooks/api/useAuth.ts
  src/pages/EditProfile/EditProfilePage.tsx
  src/pages/LanguageSetting/LanguageSettingPage.tsx
  src/pages/ManageResumePage/ManageResumePage.tsx
  src/pages/PostLanguage/PostLanguagePage.tsx
  src/pages/Profile/ProfilePage.tsx
  src/types/api/profile.ts
  src/types/api/resumes.ts
  src/types/manageResume/manageResume.ts
  src/utils/checkUserPage.ts
  src/utils/editProfileData.ts
Labels: 📭 API

#76 Feat/igw 46/68 공고등록
  src/api/post.ts
  src/components/Common/TimePicker.tsx
  src/components/Common/WorkDayTimeBottomSheet.tsx
  src/components/Employer/PostCreate/Step1.tsx
  src/components/Employer/PostCreate/Step2.tsx
  src/components/Employer/PostCreate/Step3.tsx
  src/components/Employer/PostCreate/Step4.tsx
  src/components/Employer/PostCreate/Step5.tsx
  src/components/Employer/Signup/AgreeModalInner.tsx
  src/components/Information/AddressStep.tsx
  src/components/Information/LanguageStep.tsx
  src/components/Information/StepIndicator.tsx
  src/constants/documents.ts
  src/constants/post.ts
  src/hooks/api/usePost.ts
  src/pages/Employer/Post/EmployerCreatePostPage.tsx
  src/pages/Information/InformationPage.tsx
  src/router.tsx
  src/types/api/document.ts
  src/types/postCreate/postCreate.ts
  src/utils/document.ts
  src/utils/information.ts
  src/utils/post.ts
Labels: ✨ Feature, 🎨 Html&CSS, 📭 API

#82 Feat/igw 50/77 고용주문서작성
  src/api/document.ts
  src/components/Common/Dropdown.tsx
  src/components/Common/Input.tsx
  src/components/Common/WorkDayTimeWithRestBottomSheet.tsx
  src/components/Employer/ApplicantDocumentsDetail/DocumentCardDispenserEmployer.tsx
  src/components/Employer/ApplicantDocumentsDetail/DocumentSubHeaderEmployer.tsx
  src/components/Employer/PostCreate/Step1.tsx
  src/components/Employer/PostCreate/Step2.tsx
  src/components/Employer/WriteDocument/EmployeeInfoSectionKOR.tsx
  src/components/Employer/WriteDocument/EmployerLaborContractForm.tsx
  src/components/Employer/WriteDocument/EmployerPartTimePermitForm.tsx
  src/components/Information/AddressStep.tsx
  src/components/Information/InformationStep.tsx
  src/constants/documents.ts
  src/hooks/api/useDocument.ts
  src/pages/ApplicationDocuments/ApplicationDocumentsPage.tsx
  src/pages/Employer/WriteDocuments/ApplicantDocumentsDetailPage.tsx
  src/pages/Employer/WriteDocuments/EmployerWriteDocumentsPage.tsx
  src/router.tsx
  src/types/api/document.ts
  src/types/api/users.ts
  src/types/postCreate/postCreate.ts
  src/utils/document.ts
  src/utils/employerProfile.ts
  src/utils/post.ts
  src/utils/signup.ts
Labels: ✨ Feature, 🎨 Html&CSS, 📭 API

#83 Feat/igw 49/73 - 유학생 마이페이지, auth API 연결
  src/api/auth.ts
  src/api/resumes.ts
  src/components/Language/EtcLanguageCard.tsx
  src/components/Language/EtcLanguageSection.tsx
  src/components/Language/LanguageCard.tsx
  src/components/Language/LanguageSection.tsx
  src/components/ManageResume/ResumeEditSection.tsx
  src/components/ManageResume/components/EducationDetail.tsx
  src/components/ManageResume/components/IntroductionDetail.tsx
  src/components/ManageResume/components/LanguageManageDetail.tsx
  src/components/ManageResume/components/MypageCard.tsx
  src/components/ManageResume/components/ResumeManageBox.tsx
  src/components/ManageResume/components/WorkExperienceDetail.tsx
  src/components/Profile/ApplicationStatus.tsx
  src/components/SetEducation/EducationPatch.tsx
  src/components/SetEducation/EducationPost.tsx
  src/components/SetEducation/SearchSchools.tsx
  src/components/Splash/Splash.tsx
  src/components/WorkExperience/WorkExperiencePatch.tsx
  src/components/WorkExperience/WorkExperiencePost.tsx
  src/constants/language_data.ts
  src/constants/manageResume.ts
  src/hooks/api/useAuth.ts
  src/hooks/api/useResume.ts
  src/hooks/api/useSetting.ts
  src/pages/EditProfile/EditProfilePage.tsx
  src/pages/Introduction/IntroductionPage.tsx
  src/pages/ManageResumePage/ManageResumePage.tsx
  src/pages/PostLanguage/PostLanguagePage.tsx
  src/pages/SetEducation/PatchEducationPage.tsx
  src/pages/SetEducation/PostEducationPage.tsx
  src/pages/SetWorkExperience/PatchWorkExperiencePage.tsx
  src/pages/SetWorkExperience/PostWorkExperiencePage.tsx
  src/types/api/resumes.ts
  src/types/manageResume/manageResume.ts
  src/types/postResume/postEducation.ts
  src/types/postResume/postWorkExperience.ts
  src/utils/editResume.ts
  src/utils/introduction.ts
Labels: 📭 API

#84 Feat/igw-49/73 - 회원가입 동의 모달 에러 해결 및 고용주 프로필 api
  src/components/Employer/Profile/EmployerJobInfo.tsx
  src/components/Employer/Profile/EmployerProfileCard.tsx
  src/components/Employer/Signup/AgreeModalInner.tsx
  src/components/Profile/ProfileHeader.tsx
  src/components/Profile/ProfileMenu.tsx
  src/constants/translation.ts
Labels: 📭 API

#90 🐛 fix: 고용주 프로필 API 수정 #73
  src/components/Employer/Profile/EmployerProfileMenu.tsx
  src/components/Employer/Profile/EmployerProfileMenuList.tsx
  src/components/ManageResume/ProfilePicture.tsx
  src/hooks/api/useProfile.ts
  src/pages/Employer/EditProfile/EmployerEditProfilePage.tsx
Labels: 🐞 BugFix

#91 Feat/87 고용주 서류 api 연결
  src/api/document.ts
  src/api/post.ts
  src/components/Common/Input.tsx
  src/components/Document/write/SearchSchoolBottomSheet.tsx
  src/components/Document/write/SignaturePad.tsx
  src/components/Employer/ApplicantDocumentsDetail/DocumentCardDispenserEmployer.tsx
  src/components/Employer/PostCreate/Step1.tsx
  src/components/Employer/PostCreate/Step3.tsx
  src/components/Employer/PostCreate/Step4.tsx
  src/components/Employer/PostCreate/Step5.tsx
  src/components/Employer/WriteDocument/EmployerLaborContractForm.tsx
  src/components/WriteDocuments/DocumentFormDispenser.tsx
  src/components/WriteDocuments/IntegratedApplicationWriteForm.tsx
  src/components/WriteDocuments/LaborContractWriteForm.tsx
  src/components/WriteDocuments/PartTimePermitWriteForm.tsx
  src/hooks/api/useDocument.ts
  src/hooks/api/usePost.ts
  src/pages/Employer/Post/EmployerCreatePostPage.tsx
  src/pages/Employer/WriteDocuments/ApplicantDocumentsDetailPage.tsx
  src/pages/Employer/WriteDocuments/EmployerWriteDocumentsPage.tsx
  src/router.tsx
  src/utils/document.ts
Labels: 📭 API

#93 Feat/87 고용주 서류 api 연결
  src/pages/ApplicationDocuments/ApplicationDocumentsPage.tsx
  src/pages/WriteDocuments/DocumentPreviewPage.tsx
  src/pages/WriteDocuments/RequestModifyPage.tsx
Labels: 🐞 BugFix, 📭 API

#94 [Feat/igw-44/65] 서류 수정, 공고 수정 페이지와 연결 및 신청 관리 api 연결
  src/components/ApplicationDetail/ApplicationDetailStep3.tsx
  src/components/ApplicationDetail/ApplicationDetailStep4.tsx
  src/components/ApplicationDetail/ApplicationDetailStep5.tsx
  src/components/ApplicationDetail/ApplicationDetailStep6.tsx
  src/components/Employer/ApplicantList/EmployerApplicantList.tsx
  src/components/Employer/ApplicantResumeAccept/EmployerApplicantResumeButton.tsx
  src/components/Employer/PostDetail/EmployerPostDetailButton.tsx
  src/constants/application.ts
  src/hooks/api/useApplication.ts
  src/hooks/api/usePost.ts
  src/hooks/api/useResume.ts
  src/router.tsx
Labels: 🐞 BugFix, 📭 API
