Repository Team-inglo/Giggle-Web, pull requests merged in 2024-11, with the labels that each got.

#96 Feat/87 미적용 코드 구현 및 작성
  src/components/Document/write/SignaturePad.tsx
  src/components/Employer/EditProfile/EmployerEditInputSection.tsx
  src/components/Employer/PostCreate/Step5.tsx
  src/components/Employer/Signup/InformationInputSection.tsx
  src/components/Employer/WriteDocument/EmployerLaborContractForm.tsx
  src/components/Employer/WriteDocument/EmployerPartTimePermitForm.tsx
  src/pages/Employer/WriteDocuments/EmployerWriteDocumentsPage.tsx
  src/utils/document.ts
  src/utils/signup.ts
Labels: 🐞 BugFix, 🎨 Html&CSS

#97 Fix/igw-49/73 - 고용주 회원가입 완료
  src/api/auth.ts
  src/components/Document/write/SearchSchoolBottomSheet.tsx
  src/components/Employer/EditProfile/EmployerEditInputSection.tsx
  src/components/Employer/Profile/EmployerProfileMenuList.tsx
  src/hooks/api/useAuth.ts
  src/pages/Employer/EditProfile/EmployerEditProfilePage.tsx
  src/pages/Employer/signup/EmployerSignupInfoPage.tsx
  src/pages/SetEducation/PostEducationPage.tsx
Labels: 🐞 BugFix, 📭 API

#98 fix-IGW-49/73 - 로그인 회원가입시 토큰 삭제
  src/hooks/api/useAuth.ts
  src/pages/Employer/Signup/EmployerSignupPage.tsx
  src/pages/Signin/SigninPage.tsx
  src/pages/Signup/SignupPage.tsx
Labels: 🐞 BugFix, 📭 API

#101 Feat/87 고용주 서류 api 연결
  src/api/document.ts
  src/components/Document/DocumentCard.tsx
  src/components/Document/DocumentCardList.tsx
  src/components/Employer/ApplicantDocumentsDetail/DocumentCardDispenserEmployer.tsx
  src/hooks/api/useDocument.ts
  src/pages/Employer/Post/EmployerCreatePostPage.tsx
  src/pages/Employer/WriteDocuments/ApplicantDocumentsDetailPage.tsx
Labels: 🐞 BugFix, 📭 API

#102 Fix/igw 51/99 고용주 버전 UI 한국어로 변경, 챗봇 api 연결, 서류 관리 api 연결 테스트
  src/api/document.ts
  src/components/ApplicationDetail/ApplicationDetailStep3.tsx
  src/components/ChatBot/ChatBotInput.tsx
  src/components/Common/JobPostingCard.tsx
  src/components/Common/WorkDayTimeBottomSheet.tsx
  src/components/Document/DocumentCard.tsx
  src/components/Document/DocumentCardList.tsx
  src/components/Employer/ApplicantDetail/EmployerApplicantDetailButton.tsx
  src/components/Employer/ApplicantDocumentsDetail/DocumentCardDispenserEmployer.tsx
  src/components/Employer/ApplicantResumeAccept/EmployerApplicantResumeButton.tsx
  src/components/Employer/EditProfile/EmployerEditInputSection.tsx
  src/components/Employer/PostCreate/Step5.tsx
  src/components/Employer/PostDetail/EmployerPostDetailButton.tsx
  src/components/Employer/WriteDocument/EmployerLaborContractForm.tsx
  src/components/Employer/WriteDocument/EmployerPartTimePermitForm.tsx
  src/components/Home/HomeEmployerBanner.tsx
  src/components/Home/HomeHeader.tsx
  src/components/Home/HomeJobPostingList.tsx
  src/components/Home/HomeRecommendPost.tsx
  src/components/Home/HomeRecommendPostCard.tsx
  src/components/PostDetail/PostDetailContent.tsx
  src/components/PostSearch/PostSearchResult.tsx
  src/components/Signin/SigninInputSection.tsx
  src/components/Signup/EmailInput.tsx
  src/components/Signup/SignupInput.tsx
  src/components/Signup/SignupVerification.tsx
  src/components/WriteDocuments/DocumentFormDispenser.tsx
  src/components/WriteDocuments/IntegratedApplicationWriteForm.tsx
  src/components/WriteDocuments/PartTimePermitWriteForm.tsx
  src/hooks/api/useDocument.ts
  src/pages/ApplicationDetail/ApplicationDetailPage.tsx
  src/pages/ApplicationDocuments/ApplicationDocumentsPage.tsx
  src/pages/Employer/ApplicantDetail/EmployerApplicantDetailPage.tsx
  src/pages/Employer/Post/EmployerCreatePostPage.tsx
  src/pages/Employer/Post/EmployerEditPostPage.tsx
  src/pages/Employer/WriteDocuments/ApplicantDocumentsDetailPage.tsx
  src/pages/Employer/WriteDocuments/EmployerWriteDocumentsPage.tsx
  src/pages/Home/HomePage.tsx
  src/pages/PostSearch/PostSearchPage.tsx
  src/pages/Signin/SigninPage.tsx
  src/pages/WriteDocuments/DocumentPreviewPage.tsx
  src/pages/WriteDocuments/WriteDocumentsPage.tsx
  src/router.tsx
  src/types/api/document.ts
  src/utils/document.ts
Labels: 🐞 BugFix, 🎨 Html&CSS, 📭 API

#104 🐛 fix: ts build error fix
  src/components/ApplicationDetail/ApplicationDetailStep3.tsx
  src/components/Document/DocumentCard.tsx
  src/components/Employer/ApplicantDetail/EmployerApplicantDetailButton.tsx
  src/components/Employer/ApplicantDocumentsDetail/DocumentCardDispenserEmployer.tsx
  src/components/Employer/ApplicantResumeAccept/EmployerApplicantResumeButton.tsx
  src/components/Home/HomeRecommendPostCard.tsx
  src/components/Signup/EmailInput.tsx
  src/components/Signup/SignupInput.tsx
  src/components/WriteDocuments/DocumentFormDispenser.tsx
  src/hooks/api/useDocument.ts
  src/pages/ApplicationDetail/ApplicationDetailPage.tsx
  src/pages/Signin/SigninPage.tsx
  src/pages/WriteDocuments/WriteDocumentsPage.tsx
Labels: 🐞 BugFix

#106 [Feat/igw-44/65] - 오류 수정하기
  src/api/chatbot.ts
  src/components/Alarm/AlarmCard.tsx
  src/components/ChatBot/ChatBotInput.tsx
  src/components/Common/JobPostingCard.tsx
  src/components/Common/LoadingItem.tsx
  src/components/Home/HomeHeader.tsx
  src/components/PostApply/PostApplyProfile.tsx
  src/constants/application.ts
  src/constants/chatbot.ts
  src/hooks/api/useChatBot.ts
  src/pages/ChatBot/ChatBotPage.tsx
  src/pages/Home/HomePage.tsx
  src/types/application/applicationItem.ts
  src/types/common/jobPostingItem.ts
  src/utils/application.ts
Labels: 🐞 BugFix, 🎨 Html&CSS, 📭 API

#107 [Feat/igw-44/65] 작은 에러들 처리하기
  src/components/Common/Dropdown.tsx
  src/components/Common/JobPostingCard.tsx
  src/components/Document/DocumentCardList.tsx
  src/components/Employer/ApplicantDetail/EmployerApplicantContactBottomSheet.tsx
  src/components/Employer/ApplicantResumeAccept/EmployerApplicantResumeButton.tsx
  src/components/Home/HomeRecommendPostCard.tsx
  src/components/PostApply/PostApplyButton.tsx
  src/components/PostApply/PostApplyErrorBottomSheet.tsx
  src/components/PostApply/PostApplyProfile.tsx
  src/components/PostSearch/PostSearchResult.tsx
  src/hooks/api/useApplication.ts
  src/hooks/api/usePost.ts
  src/pages/Employer/Post/EmployerCreatePostPage.tsx
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&CSS, 📭 API

#108 Fix/105 고용주유학생서류작성
  src/components/Application/ApplicationCard.tsx
  src/components/Document/DocumentCard.tsx
  src/components/Document/write/EmployeeInfoSection.tsx
  src/components/Document/write/EmployerInfoSection.tsx
  src/components/Document/write/IntegratedApplicationPreview.tsx
  src/components/Document/write/SignaturePad.tsx
  src/components/Employer/ApplicantDocumentsDetail/DocumentCardDispenserEmployer.tsx
  src/components/Employer/PostCreate/Step5.tsx
  src/components/Employer/WriteDocument/EmployeeInfoSectionKOR.tsx
  src/components/Employer/WriteDocument/EmployerLaborContractForm.tsx
  src/components/Employer/WriteDocument/EmployerPartTimePermitForm.tsx
  src/components/WriteDocuments/IntegratedApplicationWriteForm.tsx
  src/components/WriteDocuments/LaborContractWriteForm.tsx
  src/components/WriteDocuments/PartTimePermitWriteForm.tsx
  src/pages/ApplicationDetail/ApplicationDetailPage.tsx
  src/pages/ApplicationDocuments/ApplicationDocumentsPage.tsx
  src/pages/Employer/WriteDocuments/EmployerWriteDocumentsPage.tsx
  src/pages/WriteDocuments/DocumentPreviewPage.tsx
  src/store/url.ts
  src/utils/document.ts
Labels: 🐞 BugFix, 📭 API

#110 [feat/103] zustand persist 적용하기
  src/components/Employer/ApplicantDetail/EmployerApplicantContactBottomSheet.tsx
  src/hooks/api/useApplication.ts
  src/hooks/api/useAuth.ts
  src/store/postSearch.ts
  src/store/signup.ts
  src/store/url.ts
  src/store/user.ts
  src/utils/clearAllStore.ts
Labels: 🐞 BugFix, ✨ Feature

#112 [Feat/103] - 공고 관련 에러 수정하기
  src/components/Common/JobPostingCard.tsx
  src/components/PostApply/PostApplyButton.tsx
  src/pages/PostDetail/PostDetailPage.tsx
  src/pages/PostSearch/PostSearchPage.tsx
  src/utils/formatSearchFilter.ts
Labels: 🐞 BugFix

#113 [Feat/103] 무한 스크롤 적용하기
  src/api/post.ts
  src/components/Employer/ApplicantList/EmployerApplicantList.tsx
  src/components/Home/HomeJobPostingList.tsx
  src/components/PostSearch/PostSearchResult.tsx
  src/hooks/api/useAlarm.ts
  src/hooks/api/useChatBot.ts
  src/hooks/api/usePost.ts
  src/hooks/useInfiniteScroll.ts
  src/pages/Alarm/AlarmPage.tsx
  src/pages/Application/ApplicationPage.tsx
  src/pages/PostSearch/PostSearchPage.tsx
  src/types/api/post.ts
  src/utils/formatSearchFilter.ts
Labels: ✨ Feature, 📭 API

#114 [feat/103] 알람 클릭 시 해당 서류 관리 페이지로 이동 및 읽었는지 여부 판단하기
  src/components/Alarm/AlarmCard.tsx
  src/components/Home/HomeHeader.tsx
  src/hooks/api/useAlarm.ts
  src/pages/Employer/ApplicantDetail/EmployerApplicantDetailPage.tsx
  src/types/api/alarm.ts
Labels: 🐞 BugFix, 📭 API

#115 [feat/103] 불필요한 더미데이터 제거하기
  src/constants/alarm.ts
  src/constants/application.ts
  src/constants/post.ts
  src/constants/postDetail.ts
Labels: 🐞 BugFix

#116 [Feat/103] 서류 관리 페이지 이동 시 에러 및 북마크 아이콘 미리 변경하기
  src/components/Common/JobPostingCard.tsx
  src/components/Home/HomeApplicationCard.tsx
  src/components/PostDetail/PostDetailApplyButton.tsx
Labels: 🐞 BugFix, 📭 API

#117 Fix/105 고용주유학생서류작성
  src/components/Document/DocumentCard.tsx
  src/components/Document/write/IntegratedApplicationPreview.tsx
  src/components/Document/write/SearchSchoolBottomSheet.tsx
  src/components/WriteDocuments/IntegratedApplicationWriteForm.tsx
  src/pages/WriteDocuments/DocumentPreviewPage.tsx
  src/utils/document.ts
Labels: 🐞 BugFix, 📭 API

#118 [Feat/103] 고용주 지원 상태에서 상세 페이지 뒤로가기 문제 해결하기
  src/pages/Employer/ApplicantDetail/EmployerApplicantDetailPage.tsx
Labels: 🐞 BugFix

#119 Fix/109 - 마이페이지 에러 및 id,pw 상태 추가
  src/components/Splash/Splash.tsx
  src/hooks/api/useAuth.ts
  src/pages/EditProfile/EditProfilePage.tsx
  src/pages/Information/InformationPage.tsx
  src/pages/ScrappedJobPosts/ScrappedJobPostsPage.tsx
Labels: 🐞 BugFix, 📭 API

#120 :bug: fix: 공고 수정 기존 내용 자동 입력, 데이터 매핑 #105
  src/components/Employer/PostCreate/Step1.tsx
  src/components/Employer/PostCreate/Step2.tsx
  src/components/Employer/PostCreate/Step4.tsx
  src/components/Employer/PostCreate/Step5.tsx
  src/hooks/api/usePost.ts
  src/pages/Employer/Post/EmployerEditPostPage.tsx
  src/types/postCreate/postCreate.ts
Labels: 🐞 BugFix, 📭 API

#123 feat: 웹앱 브릿지 구현
  global.d.ts
  index.html
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/Employer/ApplicantDetail/EmployerApplicantContactBottomSheet.tsx
  src/router.tsx
  src/store/user.ts
  src/utils/reactNativeMessage.ts
  tsconfig.app.json
  vite.config.ts
Labels: ✨ Feature, 📭 API

#124 Webappbridge test
  src/components/Document/write/EmployeeInfoSection.tsx
  src/components/Document/write/EmployerInfoSection.tsx
  src/components/Employer/WriteDocument/EmployerLaborContractForm.tsx
  src/components/Employer/WriteDocument/EmployerPartTimePermitForm.tsx
  src/components/Splash/Splash.tsx
Labels: 🐞 BugFix, 📭 API

#125 시연 플로우 상 오류 수정
  src/components/Document/DocumentCard.tsx
  src/components/Employer/ApplicantList/EmployerApplicantCard.tsx
  src/components/Information/LanguageStep.tsx
  src/components/WriteDocuments/PartTimePermitWriteForm.tsx
  src/constants/documents.ts
  src/hooks/api/useApplication.ts
  src/hooks/api/useDocument.ts
  src/pages/ApplicationDetail/ApplicationDetailPage.tsx
  src/pages/WriteDocuments/RequestModifyPage.tsx
  src/types/api/document.ts
Labels: 🐞 BugFix, 🎨 Html&CSS

#128 🐛 fix: igw-55/127 - 유학생/고용주 서류작성 버그 해결
  src/components/Common/Input.tsx
  src/components/Document/DocumentCard.tsx
  src/components/Document/write/EmployerInfoSection.tsx
  src/components/Employer/ApplicantDocumentsDetail/DocumentCardDispenserEmployer.tsx
  src/components/Employer/WriteDocument/EmployeeInfoSectionKOR.tsx
  src/components/Employer/WriteDocument/EmployerLaborContractForm.tsx
  src/components/Home/HomeHeader.tsx
  src/constants/documents.ts
  src/hooks/api/useDocument.ts
  src/pages/WriteDocuments/DocumentPreviewPage.tsx
  src/types/api/document.ts
  src/utils/document.ts
Labels: 🐞 BugFix, 🎨 Html&CSS, 📭 API

#126 🐛 fix: 경력사항 근무기간 에러 수정 #109
  src/components/Employer/Profile/EmployerJobInfo.tsx
  src/components/Employer/Profile/EmployerProfileCard.tsx
  src/components/Language/LanguageSection.tsx
  src/components/ManageResume/components/WorkExperienceDetail.tsx
  src/components/SetEducation/SearchSchools.tsx
  src/pages/EditProfile/EditProfilePage.tsx
  src/pages/ManageResumePage/ManageResumePage.tsx
  src/pages/Profile/ProfilePage.tsx
  src/pages/ScrappedJobPosts/ScrappedJobPostsPage.tsx
  src/pages/SetEducation/PatchEducationPage.tsx
  src/pages/Signin/SigninPage.tsx
  src/utils/editResume.ts
Labels: 🐞 BugFix

#131 [Feat/igw 58/129] 홈 페이지 D-day, 공고 검색 페이지 필터 위치 수정하기
  src/components/Common/JobPostingCard.tsx
  src/components/PostSearch/PostSearchFilterList.tsx
Labels: 🐞 BugFix, 🎨 Html&CSS

#130 🐛 fix: 아르바이트 지원 step3 완료 ~ step7 오류 해결
  src/api/application.ts
  src/components/ApplicationDetail/ApplicationDetailStep7.tsx
  src/hooks/api/useApplication.ts
  src/pages/ApplicationDocuments/ApplicationDocumentsPage.tsx
  src/pages/ApplicationResult/ApplicationResultPage.tsx
Labels: 🐞 BugFix, 🎨 Html&CSS, 📭 API
