Repository Team-inglo/Giggle-Web, pull requests merged in 2024-12, with the labels that each got.

#133 [Fix/igw-59/132] 홈/공고 검색/알림 디자인 오류 수정하기
  src/components/Common/Header/TextFieldHeader.tsx
  src/components/Employer/ApplicantList/EmployerApplicantList.tsx
  src/components/Home/HomeApplicationCard.tsx
  src/components/Home/HomeJobPostingList.tsx
  src/components/Home/HomeRecommendPostCard.tsx
  src/components/PostApply/PostApplyResume.tsx
  src/components/PostDetail/PostDetailContent.tsx
  src/components/PostSearch/PostSearchFilterList.tsx
  src/components/PostSearchFilter/PostSearchFilterArea.tsx
  src/pages/Alarm/AlarmPage.tsx
  src/pages/PostSearch/PostSearchPage.tsx
  src/store/postSearch.ts
  src/utils/clearAllStore.ts
  src/utils/formatSearchFilter.ts
Labels: 🐞 BugFix, 🎨 Html&CSS

#136 [Fix/IGW-61/135] BottomSheet 닫혔을 때 원상태로 돌아오도록 수정하기
  src/components/ApplicationDetail/ApplicationDetailBottomSheet.tsx
  src/components/Common/BottomSheetLayout.tsx
  src/components/Common/WorkDayTimeBottomSheet.tsx
  src/components/Common/WorkDayTimeWithRestBottomSheet.tsx
  src/components/Employer/PostCreate/Step1.tsx
  src/components/Employer/WriteDocument/EmployerLaborContractForm.tsx
  src/components/Profile/LogoutBottomSheet.tsx
  src/hooks/useBottomSheet.ts
  src/pages/Employer/Profile/EmployerProfilePage.tsx
  src/pages/Profile/ProfilePage.tsx
Labels: 🐞 BugFix

#140 [Fix/igw 60/134] 마이페이지, 회원가입 QC 수정사항
  src/api/resumes.ts
  src/components/Language/LanguageCard.tsx
  src/components/Language/LanguageSection.tsx
  src/components/ManageResume/components/EducationDetail.tsx
  src/components/ManageResume/components/LanguageManageDetail.tsx
  src/components/PostApply/PostApplyResume.tsx
  src/components/Profile/ProfileMenu.tsx
  src/components/Signup/SignupVerification.tsx
  src/hooks/.gitkeep
  src/hooks/api/useResume.ts
  src/pages/EditProfile/EditProfilePage.tsx
  src/pages/Language/LanguagePage.tsx
  src/pages/PostLanguage/PostLanguagePage.tsx
  src/pages/SetEducation/PatchEducationPage.tsx
  src/types/postApply/resumeDetailItem.ts
  src/utils/editProfileData.ts
Labels: 🐞 BugFix, 📭 API

#141 🐛 [Fix/igw 55/127] 서류작성 관련 QC 수정사항
  pnpm-lock.yaml
  src/components/Document/write/SignaturePad.tsx
  src/components/Employer/ApplicantDocumentsDetail/DocumentCardDispenserEmployer.tsx
  src/components/Employer/EditProfile/EmployerEditInputSection.tsx
  src/components/Employer/PostCreate/Step2.tsx
  src/components/Employer/Signup/InformationInputSection.tsx
  src/components/Employer/WriteDocument/EmployerLaborContractForm.tsx
  src/components/Employer/WriteDocument/EmployerPartTimePermitForm.tsx
  src/components/Information/AddressStep.tsx
  src/components/WriteDocuments/IntegratedApplicationWriteForm.tsx
  src/components/WriteDocuments/LaborContractWriteForm.tsx
  src/components/WriteDocuments/PartTimePermitWriteForm.tsx
  src/constants/documents.ts
  src/hooks/api/useAddressSearch.ts
  src/hooks/api/useDocument.ts
  src/pages/Employer/WriteDocuments/ApplicantDocumentsDetailPage.tsx
  src/utils/document.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&CSS, 📭 API

#144 [Fix/igw-63/139] 디자인 수정 사항 및 공고 관련 QC 수정 사항
  src/components/Application/ApplicationCard.tsx
  src/components/ApplicationDetail/ApplicationDetailInfo.tsx
  src/components/Common/JobPostingCard.tsx
  src/components/Common/Navbar.tsx
  src/components/Common/SearchSortDropdown.tsx
  src/components/Employer/ApplicantList/EmployerApplicantListTitle.tsx
  src/components/Employer/EditProfile/EmployerEditInputSection.tsx
  src/components/Employer/Post/EmployerPostCard.tsx
  src/components/Employer/Signup/InformationInputSection.tsx
  src/components/Employer/WriteDocument/EmployerLaborContractForm.tsx
  src/components/Employer/WriteDocument/EmployerPartTimePermitForm.tsx
  src/components/Home/HomeJobPostingList.tsx
  src/components/Home/HomeRecommendPost.tsx
  src/components/Home/HomeRecommendPostCard.tsx
  src/components/PostDetail/PostDetailContent.tsx
  src/components/PostDetail/PostDetailTitle.tsx
  src/components/PostSearch/PostSearchFilterList.tsx
  src/components/PostSearch/PostSearchResult.tsx
  src/hooks/usePostSearch.ts
  src/pages/PostSearch/PostSearchFilterPage.tsx
  src/pages/PostSearch/PostSearchPage.tsx
  src/router.tsx
  src/store/postSearch.ts
  src/utils/formatMoney.ts
  src/utils/formatSearchFilter.ts
  src/utils/information.ts
Labels: 🐞 BugFix
