Repository Team-inglo/Giggle-Web, pull requests merged in 2025-08, with the labels that each got.

#467 Merge To main: 7월 5주차
  index.html
  src/assets/icons/Home/AppliedIcon.svg
  src/assets/icons/Home/ApplyIcon.svg
  src/assets/icons/Home/MatchesIcon.svg
  src/assets/icons/Home/RecommendPostIcon.svg
  src/assets/icons/Home/ResumeIcon.svg
  src/assets/icons/Home/SavedIcon.svg
  src/assets/icons/Home/SavedPostIcon.svg
  src/components/Common/EmployeeCard/EmployeeCard.tsx
  src/components/Common/EmployeeCard/EmployeeCardBookmark.tsx
  src/components/Common/EmployeeCard/EmployeeCardEmptyState.tsx
  src/components/Common/EmployeeCard/index.ts
  src/components/Employer/EmployeeSearch/EmployerEmployeeCardList.tsx
  src/components/Home/HomeBanner.tsx
  src/components/Home/HomeBannerCarousel.tsx
  src/components/Home/HomeCareerPostCard.tsx
  src/components/Home/HomeCareerPostingList.tsx
  src/components/Home/HomeEmployeeCardList.tsx
  src/components/Home/HomeGreetingSection.tsx
  src/components/Home/HomeJobPostingSection.tsx
  src/components/Home/HomeMenu.tsx
  src/components/Home/HomePostCard.tsx
  src/components/Home/HomeTopSection.tsx
  src/components/PostSearch/CareerCardList.tsx
  src/components/PostSearch/CareerSearchSection.tsx
  src/components/PostSearch/PostSearchFilterList.tsx
  src/constants/translation.ts
  src/hooks/api/useCareer.ts
  src/hooks/useEmployeeCard.ts
  src/hooks/useFormattedVisa.ts
  src/pages/Home/HomePage.tsx
  src/pages/PostSearch/PostSearchPage.tsx
  src/pages/Resume/ScrappedJobPostsPage.tsx
  src/types/api/career.ts
  src/utils/formatSearchFilter.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&CSS, 📭 API

#473 [Fix/472] Card 내 Tag/Divider 시각 통일 및 토큰 적용
  src/components/Common/EmployeeCard/EmployeeCard.tsx
  src/components/Common/JobPostingCard.tsx
  src/components/Home/HomeCareerPostCard.tsx
  src/components/Home/HomePostCard.tsx
  src/components/PostSearch/CareerCardList.tsx
  src/components/PostSearch/PostCardList.tsx
Labels: 🎨 Html&CSS

#475 Merge to Main: 8월 2주차
  src/components/Common/EmployeeCard/EmployeeCard.tsx
  src/components/Common/JobPostingCard.tsx
  src/components/Common/TransitionRoutes.tsx
  src/components/Home/HomeCareerPostCard.tsx
  src/components/Home/HomePostCard.tsx
  src/components/PostSearch/CareerCardList.tsx
  src/components/PostSearch/PostCardList.tsx
Labels: 🐞 BugFix, 🎨 Html&CSS
