Repository Team-inglo/Giggle-Web, pull requests merged in 2025-01, with the labels that each got.

#147 [Feat/igw-66/146] 모든 페이지 상단 메뉴를 최상단에 고정 및 IOS 폰트 굵어지는 문제 해결
  src/components/Common/Header/ActionHeader.tsx
  src/components/Common/Header/BaseHeader.tsx
  src/components/Common/Header/TextFieldHeader.tsx
  src/index.css
Labels: 🐞 BugFix

#149 🐛 fix: 검색한 도로명 주소 선택 불가 현상 수정 #148
  src/hooks/api/useAddressSearch.ts
Labels: 🐞 BugFix

#150 [Fix/igw 65/145] JWT 토큰 재발급/회원가입 리디자인 반영
  src/api/auth.ts
  src/api/index.ts
  src/components/Common/Header/B
  src/components/Signin/SigninInputSection.tsx
  src/components/Signup/EmailInput.tsx
  src/components/Signup/FindJourney.tsx
  src/components/Signup/SignupInput.tsx
  src/components/Signup/SignupVerification.tsx
  src/components/Splash/Splash.tsx
  src/constants/translation.ts
  src/pages/Signin/SigninPage.tsx
  src/pages/Signup/SignupPage.tsx
  src/router.tsx
Labels: ✨ Feature, 🎨 Html&CSS, 📭 API

#152 :bug: fix: 여러번 요청 시에 401 발생하면서 토큰 재발급되지 않는 문제
  src/api/index.ts
Labels: 🐞 BugFix

#153 feat/99 - 약관동의, 상세조회
  src/api/auth.ts
  src/components/Employer/Signup/AgreeModalInner.tsx
  src/components/Information/PolicyViewer.tsx
  src/hooks/api/useAuth.ts
  src/pages/Employer/signup/EmployerSignupInfoPage.tsx
  src/pages/Information/InformationPage.tsx
  src/types/api/auth.ts
  src/types/api/users.ts
  src/utils/document.ts
Labels: ✨ Feature, 🎨 Html&CSS, 📭 API

#154 [Fix/igw 64/127 document download] 워드 파일 미리보기 및 다운로드 기능 구현
  src/components/Document/DocumentCard.tsx
  src/components/Document/DocumentCardList.tsx
  src/components/Document/DocumentViewer.tsx
  src/components/Employer/ApplicantDocumentsDetail/DocumentCardDispenserEmployer.tsx
  src/pages/Employer/WriteDocuments/ApplicantDocumentsDetailPage.tsx
  src/pages/WriteDocuments/DocumentViewerPage.tsx
  src/router.tsx
Labels: 🐞 BugFix

#155 🐛 fix: 약관조회 변경된 api 명세 적용 #99
  src/api/auth.ts
Labels: 🐞 BugFix, 📭 API

#157 🐛 fix: 별도 문서 없는 마케팅 이용동의 약관 확인 버튼 제거 #99
  src/components/Employer/Signup/AgreeModalInner.tsx
Labels: 🎨 Html&CSS

#156 Fix/igw 64/127 고용주필수입력사항적용
  src/components/Common/Input.tsx
  src/components/Document/DocumentCard.tsx
  src/components/Document/write/IntegratedApplicationPreview.tsx
  src/components/Employer/ApplicantDocumentsDetail/DocumentCardDispenserEmployer.tsx
  src/components/Employer/PostCreate/Step1.tsx
  src/components/Employer/WriteDocument/EmployerLaborContractForm.tsx
  src/components/Employer/WriteDocument/EmployerPartTimePermitForm.tsx
  src/components/WriteDocuments/IntegratedApplicationWriteForm.tsx
  src/pages/ApplicationDocuments/ApplicationDocumentsPage.tsx
  src/pages/Employer/WriteDocuments/ApplicantDocumentsDetailPage.tsx
  src/pages/WriteDocuments/RequestModifyPage.tsx
  src/types/api/document.ts
  src/utils/document.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&CSS, 📭 API

#158 🐛 Fix/127 - 서류생성로딩처리,유효성검사강화
  src/components/Document/DocumentCard.tsx
  src/components/Document/DocumentCardList.tsx
  src/components/Information/StepIndicator.tsx
  src/components/WriteDocuments/PartTimePermitWriteForm.tsx
  src/hooks/api/useDocument.ts
  src/utils/document.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&CSS
