Repository Team-inglo/Giggle-Web, pull requests merged in 2025-03, with the labels that each got.

#215 [Feature/212] 급한 QA 반영하기
  src/components/Common/CompleteButtonModal.tsx
  src/components/Employer/PostCreate/Step1.tsx
  src/components/Employer/PostCreate/Step3.tsx
  src/components/Employer/PostCreate/Step4.tsx
  src/components/Employer/WriteDocument/EmployerLaborContractForm.tsx
  src/components/Home/HomePostCard.tsx
  src/components/Information/InformationStep.tsx
  src/components/Information/RadioButton.tsx
  src/components/Language/LanguageCard.tsx
  src/components/ManageResume/LanguageManageDetail.tsx
  src/components/PostApply/PostApplyButton.tsx
  src/components/WriteDocuments/IntegratedApplicationWriteForm.tsx
  src/pages/EditProfile/EditProfilePage.tsx
  src/pages/Employer/Post/EmployerEditPostPage.tsx
  src/pages/PostDetail/PostDetailPage.tsx
  src/types/postCreate/postCreate.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&CSS

#218 [fix/217] 근로 계약서 작성 시에 Detailed Address에 입력이 불가능한 이슈 해결하기
  src/components/WriteDocuments/IntegratedApplicationWriteForm.tsx
  src/components/WriteDocuments/LaborContractWriteForm.tsx
Labels: 🐞 BugFix

#214 [Feature/210] - 프로필 사진 수정이 안 되는 이슈 + 모든수정 화면에 대해, 기본적으로 Save를 활성화 하도록 수정
  src/components/Employer/Profile/EmployerProfileCard.tsx
  src/components/WorkExperience/WorkExperiencePatch.tsx
  src/hooks/api/useProfile.ts
  src/pages/EditProfile/EditProfilePage.tsx
  src/pages/Introduction/IntroductionPage.tsx
  src/pages/SetEducation/PatchEducationPage.tsx
  src/pages/SetWorkExperience/PatchWorkExperiencePage.tsx
Labels: 🐞 BugFix, ✨ Feature

#209 [Feature/202] 로딩/데이터가 없는 경우/서버에러 처리하기
  src/App.tsx
  src/assets/icons/EmptyJobIcon.svg
  src/assets/images/loadingGif.gif
  src/components/Common/LoadingPostItem.tsx
  src/components/Common/ServerErrorBottomSheet.tsx
  src/components/Home/HomeEmptyJobList.tsx
  src/components/Home/HomeJobPostingList.tsx
  src/components/Home/HomeJobPostingSection.tsx
  src/components/Home/HomePostCard.tsx
  src/components/PostSearch/PostSearchResult.tsx
  src/constants/translation.ts
  src/hooks/api/usePost.ts
  src/hooks/useHomeJobPosting.ts
  src/pages/Home/HomePage.tsx
  src/pages/PostSearch/PostSearchPage.tsx
  src/pages/ScrappedJobPosts/ScrappedJobPostsPage.tsx
  src/utils/signup.ts
Labels: ✨ Feature, 🎨 Html&CSS

#220 Feature/177 로그인회원가입리뉴얼
  src/components/Common/Dropdown.tsx
  src/components/Common/Input.tsx
  src/components/Employer/EditProfile/EmployerEditInputSection.tsx
  src/components/Employer/PostCreate/Step4.tsx
  src/components/Employer/WriteDocument/EmployerLaborContractForm.tsx
  src/components/Employer/WriteDocument/EmployerPartTimePermitForm.tsx
  src/components/Information/AddressStep.tsx
  src/components/WriteDocuments/IntegratedApplicationWriteForm.tsx
  src/components/WriteDocuments/LaborContractWriteForm.tsx
  src/components/WriteDocuments/PartTimePermitWriteForm.tsx
  src/pages/EditProfile/EditProfilePage.tsx
  src/utils/document.ts
Labels: ✨ Feature, 🎨 Html&CSS, 📭 API

#222 [Feature/206] 공고 등록/수정에서 비자 선택을 다중 선택으로 변경하기
  src/components/Common/JobPostingCard.tsx
  src/components/Common/VisaDropdown.tsx
  src/components/Common/VisaSelectBottomSheet.tsx
  src/components/Employer/PostCreate/Step3.tsx
  src/components/Home/HomeJobPostingSection.tsx
  src/components/Home/HomePostCard.tsx
  src/components/PostApply/PostApplyResume.tsx
  src/components/PostDetail/PostDetailContent.tsx
  src/components/PostDetail/PostDetailTitle.tsx
  src/constants/information.ts
  src/constants/post.ts
  src/constants/postSearch.ts
  src/constants/profile.ts
  src/constants/translation.ts
  src/pages/ScrappedJobPosts/ScrappedJobPostsPage.tsx
  src/types/api/users.ts
  src/types/common/jobPostingItem.ts
  src/types/postApply/resumeDetailItem.ts
  src/types/postCreate/postCreate.ts
  src/types/postDetail/postDetailItem.ts
  src/utils/formatSearchFilter.ts
Labels: ✨ Feature, 🎨 Html&CSS

#229 [Feature/212] 공고 상세 페이지 / 공고 검색 페이지 / 공고 카드 디자인 리뉴얼
  src/assets/icons/BookmarkIcon.svg
  src/assets/icons/CalendarIcon.svg
  src/assets/icons/ClockIcon.svg
  src/assets/icons/LocationIcon.svg
  src/assets/icons/MoneyIcon.svg
  src/assets/icons/Post/CompanyInformationIcon.svg
  src/assets/icons/Post/DetailedOverviewIcon.svg
  src/assets/icons/Post/RecruitmentConditionsIcon.svg
  src/assets/icons/Post/WorkingConditionsIcon.svg
  src/assets/icons/Post/WorkplaceInformationIcon.svg
  src/components/Application/ApplicationCard.tsx
  src/components/ApplicationDetail/ApplicationDetailCard.tsx
  src/components/ApplicationDetail/ApplicationDetailInfo.tsx
  src/components/Common/Header/TextFieldHeader.tsx
  src/components/Common/InfoCardLayout.tsx
  src/components/Common/JobPostingCard.tsx
  src/components/Common/SearchSortDropdown.tsx
  src/components/Common/Tag.tsx
  src/components/Common/VisaDropdown.tsx
  src/components/Common/WorkDayTimeBottomSheet.tsx
  src/components/Common/WorkDayTimeWithRestBottomSheet.tsx
  src/components/Document/write/EmployerInfoSection.tsx
  src/components/Employer/ApplicantDetail/EmployerApplicantDetailCard.tsx
  src/components/Employer/ApplicantList/EmployerApplicantCard.tsx
  src/components/Employer/ApplicantList/EmployerApplicantListTitle.tsx
  src/components/Employer/Post/EmployerPostCard.tsx
  src/components/Employer/PostDetail/EmployerPostDetailButton.tsx
  src/components/Employer/WriteDocument/EmployerLaborContractForm.tsx
  src/components/Home/HomePostCard.tsx
  src/components/PostApply/PostApplyButton.tsx
  src/components/PostApply/PostApplyResume.tsx
  src/components/PostDetail/PostDetailApplyButton.tsx
  src/components/PostDetail/PostDetailCompanyImageList.tsx
  src/components/PostDetail/PostDetailContent.tsx
  src/components/PostDetail/PostDetailContentMenuBar.tsx
  src/components/PostDetail/PostDetailTitle.tsx
  src/components/PostSearch/PostSearchFilterList.tsx
  src/components/PostSearch/PostSearchResult.tsx
  src/components/PostSearchFilter/PostSearchFilterArea.tsx
  src/components/PostSearchFilter/PostSearchFilterAreaInput.tsx
  src/components/PostSearchFilter/PostSearchFilterAreaSelect.tsx
  src/components/PostSearchFilter/PostSearchFilterBottomSheet.tsx
  src/components/PostSearchFilter/PostSearchFilterList.tsx
  src/components/PostSearchFilter/PostSearchFilterToggle.tsx
  src/hooks/api/usePost.ts
  src/pages/ApplicationDetail/ApplicationDetailPage.tsx
  src/pages/Employer/ApplicantList/EmployerApplicantListPage.tsx
  src/pages/Employer/PostDetail/EmployerPostDetailPage.tsx
  src/pages/PostDetail/PostDetailPage.tsx
  src/pages/PostSearch/PostSearchFilterPage.tsx
  src/pages/PostSearch/PostSearchPage.tsx
  src/pages/ScrappedJobPosts/ScrappedJobPostsPage.tsx
  src/types/postDetail/postDetailItem.ts
  src/utils/calculateDDay.ts
  src/utils/calculateTimeAgo.ts
  src/utils/post.ts
  tailwind.config.js
Labels: ✨ Feature, 🎨 Html&CSS

#234 Feature/224 유학생 서류확인서류작성 디자인 리뉴얼
  package.json
  pnpm-lock.yaml
  src/assets/icons/BlackFolder.svg
  src/components/Document/DocumentCard.tsx
  src/components/Document/MakeDocumentButton.tsx
  src/components/Document/write/DocumentSubHeader.tsx
  src/components/Document/write/EmployeeInfoSection.tsx
  src/components/Document/write/EmployerInfoSection.tsx
  src/components/Document/write/IntegratedApplicationPreview.tsx
  src/components/Document/write/SearchSchoolBottomSheet.tsx
  src/components/Employer/ApplicantDocumentsDetail/DocumentCardDispenserEmployer.tsx
  src/components/Employer/ApplicantDocumentsDetail/DocumentSubHeaderEmployer.tsx
  src/components/Employer/WriteDocument/EmployeeInfoSectionKOR.tsx
  src/constants/documents.ts
  src/hooks/api/useDocument.ts
  src/pages/Employer/WriteDocuments/ApplicantDocumentsDetailPage.tsx
  src/pages/Employer/WriteDocuments/EmployerWriteDocumentsPage.tsx
  src/pages/WriteDocuments/DocumentPreviewPage.tsx
  src/types/api/document.ts
  src/utils/map.tsx
Labels: 🐰 no-rabbit-zone

#241 [Feature/235] 공고 검색 / 홈 / 알림 페이지에서 고용주인 경우 한글로 변경 및 로딩 스피너 gif 적용하기
  src/assets/images/loadingSpinnerGif.gif
  src/components/Application/ApplicationPostCard.tsx
  src/components/Common/JobPostingCard.tsx
  src/components/Common/LoadingItem.tsx
  src/components/Common/Tag.tsx
  src/components/Employer/ApplicantDetail/EmployerApplicantDetailCard.tsx
  src/components/Employer/Profile/EmployerJobInfo.tsx
  src/components/Home/HomeJobPostingList.tsx
  src/components/Home/HomePostCard.tsx
  src/components/PostSearch/PostSearchFilterList.tsx
  src/components/PostSearchFilter/PostSearchFilterAreaInput.tsx
  src/components/PostSearchFilter/PostSearchFilterButtons.tsx
  src/components/PostSearchFilter/PostSearchFilterList.tsx
  src/components/Profile/ApplicationStatus.tsx
  src/constants/information.ts
  src/constants/postSearch.ts
  src/constants/translation.ts
  src/pages/Alarm/AlarmPage.tsx
  src/pages/PostSearch/PostSearchFilterPage.tsx
  src/utils/calculateTimeAgo.ts
Labels: ✨ Feature, 🎨 Html&CSS

#245 [Fix/242] - 공고 수정 시 일부 정보 초기화 수정
  src/components/Common/Dropdown.tsx
  src/components/Common/JobPostingCard.tsx
  src/components/Common/VisaDropdown.tsx
  src/components/Common/VisaSelectBottomSheet.tsx
  src/components/Employer/ApplicantResumeAccept/EmployerApplicantResumeButton.tsx
  src/components/Employer/PostCreate/Step2.tsx
  src/components/Employer/PostCreate/Step3.tsx
  src/components/Employer/PostCreate/Step4.tsx
  src/components/Employer/PostCreate/Step5.tsx
  src/components/Employer/PostDetail/EmployerPostDeleteBottomSheet.tsx
  src/components/Employer/PostDetail/EmployerPostDetailButton.tsx
  src/components/PostApply/PostApplyButton.tsx
  src/components/PostDetail/PostDetailContent.tsx
  src/components/PostSearchFilter/PostSearchFilterBottomSheet.tsx
  src/components/PostSearchFilter/PostSearchFilterButtons.tsx
  src/components/PostSearchFilter/PostSearchFilterList.tsx
  src/components/Profile/LogoutBottomSheet.tsx
  src/constants/post.ts
  src/constants/postSearch.ts
  src/constants/translation.ts
  src/pages/Employer/Post/EmployerCreatePostPage.tsx
  src/pages/Employer/Post/EmployerEditPostPage.tsx
  src/pages/PostSearch/PostSearchPage.tsx
  src/pages/SetEducation/PatchEducationPage.tsx
  src/pages/SetWorkExperience/PatchWorkExperiencePage.tsx
  src/types/postDetail/postDetailItem.ts
  src/utils/post.ts
Labels: 🐞 BugFix, 🎨 Html&CSS

#246 Merge to Main
  src/assets/images/loadingSpinnerGif.gif
  src/components/Application/ApplicationPostCard.tsx
  src/components/Common/Dropdown.tsx
  src/components/Common/JobPostingCard.tsx
  src/components/Common/LoadingItem.tsx
  src/components/Common/Tag.tsx
  src/components/Common/VisaDropdown.tsx
  src/components/Common/VisaSelectBottomSheet.tsx
  src/components/Employer/ApplicantDetail/EmployerApplicantDetailCard.tsx
  src/components/Employer/ApplicantResumeAccept/EmployerApplicantResumeButton.tsx
  src/components/Employer/PostCreate/Step2.tsx
  src/components/Employer/PostCreate/Step3.tsx
  src/components/Employer/PostCreate/Step4.tsx
  src/components/Employer/PostCreate/Step5.tsx
  src/components/Employer/PostDetail/EmployerPostDeleteBottomSheet.tsx
  src/components/Employer/PostDetail/EmployerPostDetailButton.tsx
  src/components/Employer/Profile/EmployerJobInfo.tsx
  src/components/Home/HomeJobPostingList.tsx
  src/components/Home/HomePostCard.tsx
  src/components/PostApply/PostApplyButton.tsx
  src/components/PostDetail/PostDetailContent.tsx
  src/components/PostSearch/PostSearchFilterList.tsx
  src/components/PostSearchFilter/PostSearchFilterAreaInput.tsx
  src/components/PostSearchFilter/PostSearchFilterBottomSheet.tsx
  src/components/PostSearchFilter/PostSearchFilterButtons.tsx
  src/components/PostSearchFilter/PostSearchFilterList.tsx
  src/components/Profile/ApplicationStatus.tsx
  src/components/Profile/LogoutBottomSheet.tsx
  src/constants/information.ts
  src/constants/post.ts
  src/constants/postSearch.ts
  src/constants/translation.ts
  src/pages/Alarm/AlarmPage.tsx
  src/pages/Employer/Post/EmployerCreatePostPage.tsx
  src/pages/Employer/Post/EmployerEditPostPage.tsx
  src/pages/PostSearch/PostSearchFilterPage.tsx
  src/pages/PostSearch/PostSearchPage.tsx
  src/pages/SetEducation/PatchEducationPage.tsx
  src/pages/SetWorkExperience/PatchWorkExperiencePage.tsx
  src/types/postDetail/postDetailItem.ts
  src/utils/calculateTimeAgo.ts
  src/utils/post.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&CSS

#251 [Feature/250] - 사업자등록번호 인증 시스템 추가
  src/api/auth.ts
  src/api/index.ts
  src/assets/icons/GiggleLogo.svg
  src/assets/images/GiggleLogo.png
  src/components/Employer/Signup/InformationInputSection.tsx
  src/components/Signup/SignupInput.tsx
  src/hooks/api/useAuth.ts
  src/pages/Employer/signup/EmployerSignupInfoPage.tsx
  src/types/api/common.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&CSS, 📭 API

#253 [Feature/249-banner] 홈 페이지 배너 캐러셀 및 상세 조회 구현 및 BottomSheet 오류 해결
  package.json
  pnpm-lock.yaml
  src/api/banner.ts
  src/components/Common/BottomSheetLayout.tsx
  src/components/Home/HomeBanner.tsx
  src/components/Home/HomeMenu.tsx
  src/components/PostSearch/PostSearchResult.tsx
  src/constants/translation.ts
  src/hooks/api/useBanner.ts
  src/hooks/useBottomSheet.ts
  src/pages/Home/HomeBannerPage.tsx
  src/router.tsx
  src/types/api/banner.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&CSS

#258 [Fix/257] - 공고 등록/수정 시 페이지 이동 로직 통일
  src/hooks/api/usePost.ts
  src/pages/Employer/Post/EmployerCreatePostPage.tsx
  src/pages/Employer/Post/EmployerEditPostPage.tsx
Labels: 🐞 BugFix

#260 [Feat/254] - mutation api 비동기 로딩 처리
  src/App.tsx
  src/components/Common/LoadingItem.tsx
  src/components/Document/DocumentCard.tsx
  src/components/Document/DocumentCardList.tsx
  src/components/Employer/ApplicantDocumentsDetail/DocumentCardDispenserEmployer.tsx
  src/components/Employer/ApplicantList/EmployerApplicantList.tsx
  src/components/Employer/PostCreate/Step4.tsx
  src/components/Employer/PostCreate/Step5.tsx
  src/components/Employer/WriteDocument/EmployerLaborContractForm.tsx
  src/components/Employer/WriteDocument/EmployerPartTimePermitForm.tsx
  src/components/PostApply/PostApplyResume.tsx
  src/components/PostSearch/PostSearchResult.tsx
  src/components/Splash/Splash.tsx
  src/components/WriteDocuments/IntegratedApplicationWriteForm.tsx
  src/components/WriteDocuments/LaborContractWriteForm.tsx
  src/components/WriteDocuments/PartTimePermitWriteForm.tsx
  src/hooks/api/usePost.ts
  src/pages/Alarm/AlarmPage.tsx
  src/pages/Application/ApplicationPage.tsx
  src/pages/ChatBot/ChatBotPage.tsx
  src/pages/Employer/Post/EmployerCreatePostPage.tsx
  src/pages/Employer/Post/EmployerEditPostPage.tsx
  src/pages/Employer/Post/EmployerPostPage.tsx
  src/pages/Employer/WriteDocuments/ApplicantDocumentsDetailPage.tsx
  src/pages/Employer/signup/EmployerSignupInfoPage.tsx
  src/pages/Information/InformationPage.tsx
  src/pages/ManageResumePage/EditResumePage.tsx
  src/pages/Profile/AboutPage.tsx
  src/pages/Profile/ChangePasswordPage.tsx
  src/pages/ScrappedJobPosts/ScrappedJobPostsPage.tsx
  src/pages/WriteDocuments/RequestModifyPage.tsx
Labels: 🐞 BugFix, ✨ Feature, 📭 API

#263 Merge to Main
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/api/banner.ts
  src/components/Common/BottomSheetLayout.tsx
  src/components/Common/LoadingItem.tsx
  src/components/Document/DocumentCard.tsx
  src/components/Document/DocumentCardList.tsx
  src/components/Employer/ApplicantDocumentsDetail/DocumentCardDispenserEmployer.tsx
  src/components/Employer/ApplicantList/EmployerApplicantList.tsx
  src/components/Employer/PostCreate/Step4.tsx
  src/components/Employer/PostCreate/Step5.tsx
  src/components/Employer/WriteDocument/EmployerLaborContractForm.tsx
  src/components/Employer/WriteDocument/EmployerPartTimePermitForm.tsx
  src/components/Home/HomeBanner.tsx
  src/components/Home/HomeMenu.tsx
  src/components/PostApply/PostApplyResume.tsx
  src/components/PostSearch/PostSearchResult.tsx
  src/components/Splash/Splash.tsx
  src/components/WriteDocuments/IntegratedApplicationWriteForm.tsx
  src/components/WriteDocuments/LaborContractWriteForm.tsx
  src/components/WriteDocuments/PartTimePermitWriteForm.tsx
  src/constants/translation.ts
  src/hooks/api/useBanner.ts
  src/hooks/api/usePost.ts
  src/hooks/useBottomSheet.ts
  src/pages/Alarm/AlarmPage.tsx
  src/pages/Application/ApplicationPage.tsx
  src/pages/ChatBot/ChatBotPage.tsx
  src/pages/Employer/Post/EmployerCreatePostPage.tsx
  src/pages/Employer/Post/EmployerEditPostPage.tsx
  src/pages/Employer/Post/EmployerPostPage.tsx
  src/pages/Employer/WriteDocuments/ApplicantDocumentsDetailPage.tsx
  src/pages/Employer/signup/EmployerSignupInfoPage.tsx
  src/pages/Home/HomeBannerPage.tsx
  src/pages/Information/InformationPage.tsx
  src/pages/ManageResumePage/EditResumePage.tsx
  src/pages/Profile/AboutPage.tsx
  src/pages/Profile/ChangePasswordPage.tsx
  src/pages/ScrappedJobPosts/ScrappedJobPostsPage.tsx
  src/pages/WriteDocuments/RequestModifyPage.tsx
  src/router.tsx
  src/types/api/banner.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&CSS, 📭 API

#268 ✨ feat: 디바이스 fcm 토큰 등록 로직 구현 #266
  src/App.tsx
  src/api/auth.ts
  src/hooks/api/useAuth.ts
Labels: ✨ Feature

#267 ✨ feat: 앱으로부터 메시지 수신 및 핸들링 로직 작성 #265
  src/App.tsx
  src/api/auth.ts
  src/hooks/api/useAuth.ts
  src/utils/reactNativeMessage.ts
Labels: ✨ Feature, 📭 API

#270 [Fix/269] tanstack query context error
  src/App.tsx
  src/components/Common/ReactNativeMessageListener.tsx
Labels: 🐞 BugFix

#274 [Fix/273] 전체적인 시나리오 테스트 진행 시 발생한 오류 수정하기
  src/components/Application/ApplicationCardList.tsx
  src/components/ApplicationDetail/ApplicationDetailStep2.tsx
  src/components/Common/BottomSheetLayout.tsx
  src/components/Document/write/EmployeeInfoSection.tsx
  src/components/Document/write/EmployerInfoSection.tsx
  src/components/Document/write/IntegratedApplicationPreview.tsx
  src/components/Home/HomeMenu.tsx
  src/constants/postSearch.ts
  src/pages/Employer/Post/EmployerEditPostPage.tsx
  src/utils/map.tsx
Labels: 🐞 BugFix

#278 Fix/277 - 유학생 문서 수정 시 공고 id를 보내는 현상
  src/components/WriteDocuments/IntegratedApplicationWriteForm.tsx
  src/components/WriteDocuments/LaborContractWriteForm.tsx
  src/components/WriteDocuments/PartTimePermitWriteForm.tsx
  src/hooks/api/useDocument.ts
Labels: 🐞 BugFix, 📭 API

#282 [Fix/280] - 문서 수정 전화번호 관련
  src/components/Document/write/EmployeeInfoSection.tsx
  src/components/Employer/EditProfile/EmployerEditInputSection.tsx
  src/components/Employer/PostCreate/Step2.tsx
  src/components/Employer/Signup/InformationInputSection.tsx
  src/components/Employer/WriteDocument/EmployerLaborContractForm.tsx
  src/components/Employer/WriteDocument/EmployerPartTimePermitForm.tsx
  src/components/Information/AddressStep.tsx
  src/components/WriteDocuments/IntegratedApplicationWriteForm.tsx
  src/components/WriteDocuments/LaborContractWriteForm.tsx
  src/components/WriteDocuments/PartTimePermitWriteForm.tsx
  src/constants/translation.ts
  src/pages/EditProfile/EditProfilePage.tsx
  src/utils/document.ts
  src/utils/editProfileData.ts
  src/utils/map.tsx
  src/utils/signup.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&CSS, 📭 API

#283 [Fix/281] 이력서 관리 페이지 관련 오류 수정
  src/components/Common/Dropdown.tsx
  src/components/Employer/PostCreate/Step5.tsx
  src/components/Employer/WriteDocument/EmployerLaborContractForm.tsx
  src/components/Introduction/IntroductionInput.tsx
  src/components/ManageResume/IntroductionDetail.tsx
  src/components/ManageResume/WorkExperienceDetail.tsx
  src/components/PostApply/PostApplyResume.tsx
  src/components/PostDetail/PostDetailContent.tsx
  src/components/WriteDocuments/PartTimePermitWriteForm.tsx
  src/constants/postSearch.ts
  src/constants/translation.ts
  src/pages/ApplicationResult/ApplicationResultPage.tsx
  src/pages/Introduction/IntroductionPage.tsx
  src/pages/WriteDocuments/RequestModifyPage.tsx
  src/utils/information.ts
Labels: 🐞 BugFix

#286 [Fix/285] 서류 신청 관리 오류 수정 및 급한 QA 반영하기
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/ApplicationDetail/ApplicationDetailStep4.tsx
  src/components/ApplicationDetail/ApplicationDetailStep5.tsx
  src/components/ApplicationDetail/ApplicationDetailStep6.tsx
  src/components/ApplicationDetail/ApplicationDetailStep7.tsx
  src/components/Common/ApiErrorBottomSheet.tsx
  src/components/Common/Input.tsx
  src/components/WriteDocuments/IntegratedApplicationWriteForm.tsx
  src/components/WriteDocuments/LaborContractWriteForm.tsx
  src/constants/translation.ts
  src/pages/ApplicationDocuments/ApplicationDocumentsPage.tsx
  src/utils/document.ts
  src/utils/map.tsx
Labels: 🐞 BugFix

#291 [Fix/289]-디바이스id,토큰등록함수양식변경
  src/App.tsx
  src/api/auth.ts
  src/components/Common/ReactNativeMessageListener.tsx
  src/router.tsx
Labels: 🐞 BugFix, 📭 API
