Repository Team-inglo/Giggle-Web, pull requests merged in 2025-06, with the labels that each got.

#371 Feature/368 사용자 이력서 공개 여부 선택 기능 추가
  .github/workflows/test-report.yml
  .github/workflows/test.yml
  .gitignore
  package.json
  pnpm-lock.yaml
  src/__tests__/integration/resume-public.test.tsx
  src/__tests__/mocks/resume.mock.ts
  src/api/resumes.test.ts
  src/api/resumes.ts
  src/components/Common/BottomSheetLayout.tsx
  src/components/Common/ProfileImage.tsx
  src/components/Common/ToggleButton.tsx
  src/components/ManageResume/ResumeProfileCard.tsx
  src/components/PostApply/PostApplyResume.tsx
  src/components/Profile/ProfileMenu.tsx
  src/hooks/api/useResume.test.ts
  src/hooks/api/useResume.ts
  src/types/api/resumes.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&CSS, 📭 API, ✅ Test

#375 Fix/374
  src/pages/PostSearch/PostSearchPage.tsx
Labels: 🎨 Html&CSS

#378 Feature/369 인재 이력서 조회 페이지 구현
  .github/workflows/test.yml
  src/__tests__/mocks/resume.mock.ts
  src/__tests__/mocks/talent.mock.ts
  src/__tests__/utils/api-mocks.ts
  src/api/resumes.ts
  src/assets/icons/ThreeDots.svg
  src/components/Information/InformationStep.tsx
  src/components/Language/LanguageCard.tsx
  src/components/ManageResume/BookmarkContactPanel.test.tsx
  src/components/ManageResume/BookmarkContactPanel.tsx
  src/components/ManageResume/EducationDetail.tsx
  src/components/ManageResume/IntroductionDetail.tsx
  src/components/ManageResume/LanguageManageDetail.tsx
  src/components/ManageResume/MypageCard.tsx
  src/components/ManageResume/ResumeDeleteModal.tsx
  src/components/ManageResume/WorkExperienceDetail.tsx
  src/components/ManageResume/WorkPreferenceDetail.tsx
  src/components/PostApply/PostApplyResume.test.tsx
  src/components/PostApply/PostApplyResume.tsx
  src/components/TestExample/Button.test.tsx
  src/components/TestExample/Button.tsx
  src/components/WorkPreference/WorkPreferenceJobTypeSelect.tsx
  src/constants/documents.ts
  src/constants/information.ts
  src/constants/manageResume.ts
  src/constants/translation.ts
  src/hooks/api/useResume.ts
  src/pages/EditProfile/EditProfilePage.tsx
  src/pages/Resume/EmploySearchDetailPage.test.tsx
  src/pages/Resume/EmploySearchDetailPage.tsx
  src/pages/Resume/ManageResumePage.tsx
  src/pages/Resume/SetEducation/EducationPage.tsx
  src/pages/Resume/WorkPreferencePage.tsx
  src/router.tsx
  src/types/postApply/resumeDetailItem.ts
  src/utils/editResume.ts
  src/utils/resume.test.ts
  src/utils/resume.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&CSS, 📭 API, ✅ Test

#379 Fix/376
  src/assets/icons/HomeIcon.svg
  src/assets/icons/NavApplicantsIcon.svg
  src/assets/icons/NavScrappedIcon.svg
  src/assets/icons/NavSearchIcon.svg
  src/assets/icons/ProfileIcon.svg
  src/components/Common/Navbar.tsx
  src/constants/routes.ts
  src/pages/Employer/ApplicantScrapped/EmployerApplicantScrappedPage.tsx
  src/router.tsx
Labels: 🎨 Html&CSS

#382 [Feat/364] 고용주의 인재 검색 페이지 구현
  src/api/resumes.ts
  src/assets/icons/BottomSheetCheckIcon.tsx
  src/assets/icons/DisclosureIcon.tsx
  src/assets/icons/PostSearch/DownArrowIcon.svg
  src/assets/icons/PostSearch/DownArrowIcon.tsx
  src/assets/icons/ResetIcon.svg
  src/components/ApplicationDetail/ApplicationDetailBottomSheet.tsx
  src/components/ApplicationDetail/ContactHikoreaBottomSheet.tsx
  src/components/ApplicationDetail/ContactRecruiterBottomSheet.tsx
  src/components/Common/ApiErrorBottomSheet.tsx
  src/components/Common/BottomSheetLayout.tsx
  src/components/Common/LoginBottomSheet.tsx
  src/components/Common/SearchSortDropdown.tsx
  src/components/Common/ServerErrorBottomSheet.tsx
  src/components/Common/VisaSelectBottomSheet.tsx
  src/components/Common/WorkDayTimeBottomSheet.tsx
  src/components/Common/WorkDayTimeWithRestBottomSheet.tsx
  src/components/Employer/ApplicantDetail/EmployerApplicantContactBottomSheet.tsx
  src/components/Employer/EmployeeSearch/EmployerEmployeeCardList.tsx
  src/components/Employer/EmployeeSearch/EmployerEmployeeSearchFilterBottomSheet.tsx
  src/components/Employer/EmployeeSearch/EmployerEmployeeSearchSortBottomSheet.tsx
  src/components/Employer/PostDetail/EmployerPostDeleteBottomSheet.tsx
  src/components/Home/ComingSoonBottomSheet.tsx
  src/components/Home/LoginBottomSheet.tsx
  src/components/Language/LanguageCard.tsx
  src/components/Language/LevelBottomSheet.tsx
  src/components/ManageResume/BookmarkContactPanel.tsx
  src/components/ManageResume/ResumeDeleteModal.tsx
  src/components/PostApply/PostApplyErrorBottomSheet.tsx
  src/components/PostDetail/PostDetailConfirmBottomSheet.tsx
  src/components/PostSearchFilter/PostSearchFilterBottomSheet.tsx
  src/components/PostSearchFilter/PostSearchFilterToggle.tsx
  src/components/Profile/LogoutBottomSheet.tsx
  src/components/WriteDocuments/IntegratedApplicationWriteForm.tsx
  src/constants/manageResume.ts
  src/constants/postSearch.ts
  src/hooks/api/useResume.ts
  src/pages/Employer/EmployeeSearch/EmployerEmployeeSearchPage.tsx
  src/pages/Employer/Signup/EmployerSignupInfoPage.tsx
  src/pages/Information/InformationPage.tsx
  src/router.tsx
  src/types/api/resumes.ts
  src/utils/formatSearchFilter.ts
  src/utils/resume.ts
Labels: ✨ Feature, 🎨 Html&CSS

#385 Fix/384 이력서 조회 api 통합 적용
  src/api/resumes.ts
  src/components/Application/ApplicationCardList.tsx
  src/components/Employer/ApplicantList/EmployerApplicantCard.tsx
  src/components/ManageResume/BookmarkContactPanel.test.tsx
  src/components/ManageResume/BookmarkContactPanel.tsx
  src/components/PostApply/PostApplyResume.test.tsx
  src/hooks/api/useResume.ts
  src/hooks/useResumeData.ts
  src/pages/Application/ApplicationPage.tsx
  src/pages/Resume/EmploySearchDetailPage.test.tsx
  src/pages/Resume/EmploySearchDetailPage.tsx
  src/types/api/resumes.ts
  src/types/application/applicationItem.ts
Labels: 🐞 BugFix, 🎨 Html&CSS, 📭 API, ✅ Test

#386 Fix/380 - 공고 생성 시 주소 입력 불가 현상 수정
  index.html
  src/App.tsx
  src/components/Document/write/input/AddressInput.tsx
  src/components/Employer/EditProfile/EmployerEditInputSection.tsx
  src/components/Employer/Signup/InformationInputSection.tsx
  src/components/Information/AddressStep.tsx
  src/components/PostDetail/PostDetailContent.tsx
  src/constants/post.ts
  src/pages/EditProfile/EditProfilePage.tsx
  src/types/postCreate/postCreate.ts
  src/utils/map.tsx
Labels: 🐞 BugFix, 🎨 Html&CSS, 📭 API

#392 [Feat/388] 고용주의 인재 스크랩 페이지 구현
  src/api/resumes.ts
  src/components/Common/JobPostingCard.tsx
  src/components/Employer/EmployeeSearch/EmployerEmployeeCardList.tsx
  src/components/Home/HomeMenu.tsx
  src/components/PostDetail/PostDetailApplyButton.tsx
  src/components/PostSearch/CareerSearchSection.tsx
  src/components/PostSearch/PostSearchSection.tsx
  src/hooks/api/useCareer.ts
  src/hooks/api/usePost.ts
  src/hooks/api/useResume.ts
  src/pages/Employer/ApplicantScrapped/EmployerApplicantScrappedPage.tsx
  src/pages/Employer/EmployeeSearch/EmployerEmployeeSearchPage.tsx
  src/pages/Employer/Scrapped/EmployerScrappedPage.tsx
  src/pages/Resume/ScrappedJobPostsPage.tsx
  src/router.tsx
  src/types/api/career.ts
  src/types/api/post.ts
  src/types/api/resumes.ts
Labels: ✨ Feature

#390 Fix/389 Navbar-아이콘 스타일 변경
  src/assets/icons/HomeIcon.svg
  src/assets/icons/NavApplicantsIcon.svg
  src/assets/icons/NavScrappedIcon.svg
  src/assets/icons/NavSearchIcon.svg
  src/assets/icons/ProfileIcon.svg
  src/components/Common/Navbar.test.tsx
  src/components/Common/Navbar.tsx
  src/components/Common/Tag.tsx
  src/pages/Employer/EmployeeSearch/EmployerEmployeeSearchPage.tsx
  tsconfig.json
Labels: 🎨 Html&CSS

#402 Merge To main: 6월 2주차 스프린트
  README.md
  index.html
  src/assets/icons/ArrowUp.svg
  src/assets/icons/BottomSheetCheckIcon.svg
  src/assets/icons/DisclosureIcon.svg
  src/assets/icons/DownArrowIcon.svg
  src/assets/icons/Home/AlarmIcon.svg
  src/assets/icons/Home/TranslateIcon.svg
  src/assets/icons/HomeIcon.svg
  src/assets/icons/InfoCircle.svg
  src/assets/icons/NavApplicantsIcon.svg
  src/assets/icons/NavScrappedIcon.svg
  src/assets/icons/NavSearchIcon.svg
  src/assets/icons/PostSearch/DownArrowIconSm.svg
  src/assets/icons/ProfileIcon.svg
  src/assets/icons/TagCheckIcon.svg
  src/assets/icons/TagDeleteIcon.svg
  src/assets/icons/Warning.svg
  src/components/Common/BottomSheetLayout.tsx
  src/components/Common/CompleteButtonModal.tsx
  src/components/Common/Dropdown.tsx
  src/components/Common/InfoBanner.test.tsx
  src/components/Common/InfoBanner.tsx
  src/components/Common/Navbar.test.tsx
  src/components/Common/Navbar.tsx
  src/components/Common/Tag.tsx
  src/components/Employer/EmployeeSearch/EmployerEmployeeCardList.tsx
  src/components/Home/HomeBanner.tsx
  src/components/Home/HomeHeader.test.tsx
  src/components/Home/HomeHeader.tsx
  src/components/Home/HomeMenu.tsx
  src/components/Home/LanguageBottomSheet.test.tsx
  src/components/Home/LanguageBottomSheet.tsx
  src/components/Language/LanguageCard.tsx
  src/components/ManageResume/MypageCard.test.tsx
  src/components/ManageResume/MypageCard.tsx
  src/components/ManageResume/ResumeDeleteModal.tsx
  src/components/PostDetail/PostDetailCompanyImageList.tsx
  src/components/PostDetail/PostDetailImageList.tsx
  src/components/PostSearch/CareerCardList.tsx
  src/components/Profile/DeleteModal.tsx
  src/components/SetEducation/SearchSchools.tsx
  src/constants/postSearch.ts
  src/constants/routes.ts
  src/hooks/useBodyScrollLock.ts
  src/pages/Employer/EmployeeSearch/EmployerEmployeeSearchPage.tsx
  src/pages/Employer/PostDetail/EmployerPostDetailPage.tsx
  src/pages/PostDetail/CareerDetailPage.tsx
  src/pages/PostDetail/PostDetailPage.tsx
  src/pages/PostSearch/PostSearchPage.tsx
  src/types/api/career.ts
  src/types/common/infoBanner.ts
  src/utils/translate.ts
  tailwind.config.js
  tsconfig.json
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&CSS, 🥰 Accessibility, 📭 API, ✅ Test

#410 feat: :sparkles: 일반 회원 리팩토링
  src/api/career.ts
  src/components/PostSearch/CareerCardList.tsx
  src/hooks/api/useCareer.ts
  src/pages/Resume/ScrappedJobPostsPage.tsx
  src/utils/convertKeysToKebabCase.ts
  src/utils/formatSearchFilter.ts
Labels: ✨ Feature, 🎨 Html&CSS

#427 Merge to main: hotfix #425
  src/components/Common/Button.tsx
Labels: 🐞 BugFix, 🎨 Html&CSS, 🐰 no-rabbit-zone

#416 Feature/415 이력서 완성 조건 분기 처리 UI 추가
  src/api/resumes.ts
  src/components/Home/HomeBanner.tsx
  src/components/ManageResume/ResumeHelperBanner.test.tsx
  src/components/ManageResume/ResumeHelperBanner.tsx
  src/components/Profile/ApplicationStatus.tsx
  src/hooks/api/useResume.ts
  src/pages/Resume/ManageResumePage.tsx
  src/types/api/resumes.ts
Labels: ✨ Feature, 🎨 Html&CSS, 📭 API

#433 Feature/432 progress stepper 컴포넌트 추가
  src/components/Common/ProgressStepper.test.tsx
  src/components/Common/ProgressStepper.tsx
  src/components/ManageResume/ResumeHelperBanner.tsx
  src/hooks/api/useResume.ts
  src/pages/Employer/Post/EmployerPostFormPage.tsx
  src/pages/Information/InformationPage.tsx
Labels: 🐞 BugFix, 🎨 Html&CSS
