Repository Team-inglo/Giggle-Web, pull requests merged in 2025-02, with the labels that each got.

#163 [Fix/159] 토큰 재발급, coordinator 찾기에서 null 처리, 웹뷰 뒤로가기 문제 해결하기
  src/api/index.ts
  src/components/ApplicationDetail/ContactCoordinatorModal.tsx
  src/components/Common/ScrollToTop.tsx
Labels: 🐞 BugFix

#165 :bug: fix: 로그인 페이지에서 하단 버튼과 설명글이 최하단에 고정하지 않도록 수정하기 #164
  src/components/Signin/SigninInputSection.tsx
Labels: 🐞 BugFix, 🎨 Html&CSS

#169 [Fix/168] 상단 헤더 불투명도 및 사업자 등록번호 로직 수정하기
  src/components/Common/Header/B
  src/components/Common/Header/BaseHeader.tsx
  src/components/PostDetail/PostDetailCompanyImageList.tsx
  src/utils/information.ts
Labels: 🐞 BugFix

#167 Fix/166 프로필수정주소추가
  src/components/Employer/EditProfile/EmployerEditInputSection.tsx
  src/components/Employer/PostCreate/Step2.tsx
  src/components/Employer/Signup/InformationInputSection.tsx
  src/components/Employer/WriteDocument/EmployerLaborContractForm.tsx
  src/components/Employer/WriteDocument/EmployerPartTimePermitForm.tsx
  src/components/Information/AddressStep.tsx
  src/components/WriteDocuments/IntegratedApplicationWriteForm.tsx
  src/components/WriteDocuments/LaborContractWriteForm.tsx
  src/hooks/api/useAddressSearch.ts
  src/pages/EditProfile/EditProfilePage.tsx
  src/pages/Employer/EditProfile/EmployerEditProfilePage.tsx
  src/types/api/profile.ts
  src/types/postCreate/postCreate.ts
  src/utils/editProfileData.ts
  src/utils/employerProfile.ts
Labels: ✨ Feature, 🎨 Html&CSS, 📭 API

#171 [Fix/170] BottomSheet에서 window.innerHeight를 렌더링된 후 사용하도록 수정
  src/components/Common/BottomSheetLayout.tsx
Labels: 🐞 BugFix

#173 Feature/172 회원가입프로필내선택입력사항적용
  src/components/Common/BottomSheetLayout.tsx
  src/components/Common/Dropdown.tsx
  src/components/Common/Header/BaseHeader.tsx
  src/components/Common/Input.tsx
  src/components/Information/AddressStep.tsx
  src/components/Information/InformationStep.tsx
  src/components/WorkExperience/InputLayout.tsx
  src/pages/Information/InformationPage.tsx
  src/utils/information.ts
Labels: ✨ Feature, 🎨 Html&CSS

#174 Feature/172 회원가입프로필내선택입력사항적용
  src/assets/icons/Profile/GreyPenIcon.svg
  src/components/Common/Input.tsx
  src/components/Employer/Profile/EmployerJobInfo.tsx
  src/components/Employer/Profile/EmployerProfileCard.tsx
  src/components/Employer/Profile/EmployerProfileMenu.tsx
  src/components/Employer/Profile/EmployerProfileMenuList.tsx
  src/components/Information/PolicyViewer.tsx
  src/components/Profile/ApplicationStatus.tsx
  src/components/Profile/DeleteModal.tsx
  src/components/Profile/EditProfilePicture.tsx
  src/components/Profile/ProfileCard.tsx
  src/components/Profile/ProfileMenu.tsx
  src/components/Profile/ProfileMenuList.tsx
  src/constants/translation.ts
  src/pages/EditProfile/EditProfilePage.tsx
  src/pages/Employer/Profile/EmployerProfilePage.tsx
  src/pages/Profile/AboutPage.tsx
  src/pages/Profile/AccountPage.tsx
  src/pages/Profile/ProfilePage.tsx
  src/router.tsx
  src/utils/editProfileData.ts
Labels: ✨ Feature, 🎨 Html&CSS, 📭 API

#175 Dev
  src/assets/icons/Profile/GreyPenIcon.svg
  src/components/Common/BottomSheetLayout.tsx
  src/components/Common/Dropdown.tsx
  src/components/Common/Header/BaseHeader.tsx
  src/components/Common/Input.tsx
  src/components/Employer/Profile/EmployerJobInfo.tsx
  src/components/Employer/Profile/EmployerProfileCard.tsx
  src/components/Employer/Profile/EmployerProfileMenu.tsx
  src/components/Employer/Profile/EmployerProfileMenuList.tsx
  src/components/Information/AddressStep.tsx
  src/components/Information/InformationStep.tsx
  src/components/Information/PolicyViewer.tsx
  src/components/Profile/ApplicationStatus.tsx
  src/components/Profile/DeleteModal.tsx
  src/components/Profile/EditProfilePicture.tsx
  src/components/Profile/ProfileCard.tsx
  src/components/Profile/ProfileMenu.tsx
  src/components/Profile/ProfileMenuList.tsx
  src/components/WorkExperience/InputLayout.tsx
  src/constants/translation.ts
  src/pages/EditProfile/EditProfilePage.tsx
  src/pages/Employer/Profile/EmployerProfilePage.tsx
  src/pages/Information/InformationPage.tsx
  src/pages/Profile/AboutPage.tsx
  src/pages/Profile/AccountPage.tsx
  src/pages/Profile/ProfilePage.tsx
  src/router.tsx
  src/utils/editProfileData.ts
  src/utils/information.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&CSS, 📭 API

#179 [Feature/176] - 이력서 관리 페이지 디자인 수정사항 반영하기
  src/assets/icons/ManageResume/BlackPlusIcon.svg
  src/assets/icons/ManageResume/DeleteIcon.svg
  src/assets/icons/ManageResume/EditIcon.svg
  src/assets/icons/YellowDocumentIcon.svg
  src/components/Common/Button.tsx
  src/components/Common/InfoCardLayout.tsx
  src/components/Employer/Profile/EmployerJobInfo.tsx
  src/components/Introduction/IntroductionInput.tsx
  src/components/Language/LanguageCard.tsx
  src/components/Language/LanguageSection.tsx
  src/components/ManageResume/EducationDetail.tsx
  src/components/ManageResume/IntroductionDetail.tsx
  src/components/ManageResume/LanguageManageDetail.tsx
  src/components/ManageResume/MypageCard.tsx
  src/components/ManageResume/MypageCardSection.tsx
  src/components/ManageResume/ResumeDeleteModal.tsx
  src/components/ManageResume/ResumeEditSection.tsx
  src/components/ManageResume/WorkExperienceDetail.tsx
  src/components/ManageResume/components/EducationDetail.tsx
  src/components/ManageResume/components/IntroductionDetail.tsx
  src/components/ManageResume/components/LanguageManageDetail.tsx
  src/components/ManageResume/components/MypageCard.tsx
  src/components/ManageResume/components/WorkExperienceDetail.tsx
  src/components/PostApply/PostApplyResume.tsx
  src/components/Profile/ApplicationStatus.tsx
  src/components/WorkExperience/WorkExperiencePatch.tsx
  src/components/WorkExperience/WorkExperiencePost.tsx
  src/constants/profile.ts
  src/constants/translation.ts
  src/hooks/api/useResume.ts
  src/pages/Introduction/IntroductionPage.tsx
  src/pages/Language/LanguagePage.tsx
  src/pages/ManageResumePage/EditResumePage.tsx
  src/pages/ManageResumePage/ManageResumePage.tsx
  src/pages/PostLanguage/PostLanguagePage.tsx
  src/pages/SetWorkExperience/PatchWorkExperiencePage.tsx
  src/pages/SetWorkExperience/PostWorkExperiencePage.tsx
  src/router.tsx
  src/types/postApply/resumeDetailItem.ts
Labels: ✨ Feature, 🎨 Html&CSS

#181 Feature/177 로그인회원가입리뉴얼
  src/assets/icons/SignupStroke.svg
  src/components/Common/Dropdown.tsx
  src/components/Common/Header/BaseHeader.tsx
  src/components/Common/Input.tsx
  src/components/Common/PageTitle.tsx
  src/components/Employer/Profile/EmployerJobInfo.tsx
  src/components/Employer/Profile/EmployerProfileCard.tsx
  src/components/Employer/Profile/EmployerProfileMenuList.tsx
  src/components/Employer/Signup/InformationInputSection.tsx
  src/components/Information/AddressStep.tsx
  src/components/Information/InformationStep.tsx
  src/components/Information/LanguageStep.tsx
  src/components/Profile/ApplicationStatus.tsx
  src/components/Profile/EditProfilePicture.tsx
  src/components/Profile/LicenseCard.tsx
  src/components/Profile/ProfileCard.tsx
  src/components/Profile/ProfileMenuList.tsx
  src/components/Signin/SigninInputSection.tsx
  src/components/Signup/FindJourney.tsx
  src/components/Signup/SignupInput.tsx
  src/components/Signup/SignupVerification.tsx
  src/components/Signup/VerificationSuccessful.tsx
  src/constants/information.ts
  src/constants/translation.ts
  src/constants/user.ts
  src/hooks/api/useAuth.ts
  src/pages/Employer/Signup/EmployerSignupPage.tsx
  src/pages/Employer/signup/EmployerSignupInfoPage.tsx
  src/pages/Information/InformationPage.tsx
  src/pages/Profile/AboutPage.tsx
  src/pages/Profile/AccountPage.tsx
  src/pages/Signin/SigninPage.tsx
  src/pages/Signup/SignupPage.tsx
  src/types/api/auth.ts
  src/utils/signin.ts
  tailwind.config.js
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&CSS

#182 [Feature/180] 홈 페이지 디자인 수정사항 반영하기
  src/assets/icons/Home/AlarmIcon.svg
  src/assets/icons/Home/ApplyIcon.svg
  src/assets/icons/Home/HeaderLogoIcon.svg
  src/assets/icons/Home/RecommendPostIcon.svg
  src/assets/icons/Home/ResumeIcon.svg
  src/assets/icons/Home/SavedPostIcon.svg
  src/assets/images/HomeBanner.png
  src/components/Common/BottomSheetLayout.tsx
  src/components/Common/Tag.tsx
  src/components/Home/ComingSoonBottomSheet.tsx
  src/components/Home/HomeBanner.tsx
  src/components/Home/HomeEmployerBanner.tsx
  src/components/Home/HomeGuestBanner.tsx
  src/components/Home/HomeHeader.tsx
  src/components/Home/HomeJobPostingList.tsx
  src/components/Home/HomeMenu.tsx
  src/components/Home/HomePostCard.tsx
  src/components/Home/LoginBottomSheet.tsx
  src/constants/translation.ts
  src/pages/Home/HomePage.tsx
  src/types/common/jobPostingItem.ts
Labels: ✨ Feature, 🎨 Html&CSS

#192 [Feature/190] BottomButtonPanel 디자인 수정사항 반영 및 공통으로 적용하기
  src/components/Common/BottomButtonPanel.tsx
  src/components/Employer/ApplicantResumeAccept/EmployerApplicantResumeButton.tsx
  src/components/Employer/PostDetail/EmployerPostDetailButton.tsx
  src/components/PostApply/PostApplyButton.tsx
  src/components/PostDetail/PostDetailApplyButton.tsx
  src/components/WorkExperience/WorkExperiencePatch.tsx
  src/components/WorkExperience/WorkExperiencePost.tsx
  src/pages/ApplicationResult/ApplicationResultPage.tsx
  src/pages/EditProfile/EditProfilePage.tsx
  src/pages/Introduction/IntroductionPage.tsx
  src/pages/PostLanguage/PostLanguagePage.tsx
  src/pages/SetEducation/PatchEducationPage.tsx
  src/pages/SetEducation/PostEducationPage.tsx
  src/pages/SetWorkExperience/PatchWorkExperiencePage.tsx
  src/pages/SetWorkExperience/PostWorkExperiencePage.tsx
  tailwind.config.js
Labels: ✨ Feature, 🎨 Html&CSS

#194 [Feature/193] - 비로그인 상태에서 알림 버튼 클릭 시 로그인 모달 추가
  src/components/Common/BottomSheetLayout.tsx
  src/components/Home/HomeHeader.tsx
Labels: 🐞 BugFix, ✨ Feature

#195 ✨ Feat/178 아이디/비밀번호찾기
  src/api/auth.ts
  src/components/Common/CompleteModal.tsx
  src/components/Employer/Signup/AgreeModalInner.tsx
  src/components/Profile/Password/CurrentPasswordStep.tsx
  src/components/Profile/Password/NewPasswordStep.tsx
  src/components/Profile/Password/SuccessStep.tsx
  src/components/Signin/SigninInputSection.tsx
  src/constants/translation.ts
  src/hooks/api/useAuth.ts
  src/pages/Profile/AccountPage.tsx
  src/pages/Profile/ChangePasswordPage.tsx
  src/pages/Signin/ResetPasswordPage.tsx
  src/router.tsx
  src/types/api/auth.ts
  src/utils/signin.ts
  tailwind.config.js
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&CSS, 📭 API

#196 Merge to main
  src/api/auth.ts
  src/components/Common/BottomButtonPanel.tsx
  src/components/Common/BottomSheetLayout.tsx
  src/components/Common/CompleteModal.tsx
  src/components/Employer/ApplicantResumeAccept/EmployerApplicantResumeButton.tsx
  src/components/Employer/PostDetail/EmployerPostDetailButton.tsx
  src/components/Employer/Signup/AgreeModalInner.tsx
  src/components/Home/HomeHeader.tsx
  src/components/PostApply/PostApplyButton.tsx
  src/components/PostDetail/PostDetailApplyButton.tsx
  src/components/Profile/Password/CurrentPasswordStep.tsx
  src/components/Profile/Password/NewPasswordStep.tsx
  src/components/Profile/Password/SuccessStep.tsx
  src/components/Signin/SigninInputSection.tsx
  src/components/WorkExperience/WorkExperiencePatch.tsx
  src/components/WorkExperience/WorkExperiencePost.tsx
  src/constants/translation.ts
  src/hooks/api/useAuth.ts
  src/pages/ApplicationResult/ApplicationResultPage.tsx
  src/pages/EditProfile/EditProfilePage.tsx
  src/pages/Introduction/IntroductionPage.tsx
  src/pages/PostLanguage/PostLanguagePage.tsx
  src/pages/Profile/AccountPage.tsx
  src/pages/Profile/ChangePasswordPage.tsx
  src/pages/SetEducation/PatchEducationPage.tsx
  src/pages/SetEducation/PostEducationPage.tsx
  src/pages/SetWorkExperience/PatchWorkExperiencePage.tsx
  src/pages/SetWorkExperience/PostWorkExperiencePage.tsx
  src/pages/Signin/ResetPasswordPage.tsx
  src/router.tsx
  src/types/api/auth.ts
  src/utils/signin.ts
  tailwind.config.js
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&CSS, 📭 API

#200 [fix/199] useBottomSheet, BottomSheetLayout 개선하기
  src/components/Common/BottomSheetLayout.tsx
  src/hooks/useBottomSheet.ts
Labels: 🐞 BugFix

#201 [Feature/198] 마이페이지 관련 QA 및 Typography 변경사항 반영하기
  src/components/Application/ApplicationCard.tsx
  src/components/ApplicationDetail/ApplicationDetailInfo.tsx
  src/components/ApplicationDetail/ApplicationDetailStepBarLayout.tsx
  src/components/ApplicationDetail/ContactCoordinatorModal.tsx
  src/components/ApplicationDetail/ContactRecruiterModal.tsx
  src/components/Common/JobPostingCard.tsx
  src/components/Common/LoginBottomSheet.tsx
  src/components/Common/SearchSortDropdown.tsx
  src/components/Common/SubHeader.tsx
  src/components/Document/DocumentCard.tsx
  src/components/Document/write/InfoAlert.tsx
  src/components/Employer/ApplicantDetail/EmployerApplicantContactBottomSheet.tsx
  src/components/Employer/ApplicantDetail/EmployerApplicantDetailCard.tsx
  src/components/Employer/ApplicantDocumentsDetail/DocumentCardDispenserEmployer.tsx
  src/components/Employer/ApplicantList/EmployerApplicantCard.tsx
  src/components/Employer/ApplicantList/EmployerApplicantListTitle.tsx
  src/components/Employer/Post/EmployerPostCard.tsx
  src/components/Employer/Profile/EmployerProfileCard.tsx
  src/components/Home/HomeApplicationCard.tsx
  src/components/Home/HomeJobPostingList.tsx
  src/components/Home/HomePostCard.tsx
  src/components/Home/HomeRecommendPost.tsx
  src/components/Home/HomeRecommendPostCard.tsx
  src/components/Introduction/IntroductionInput.tsx
  src/components/Language/LanguageCard.tsx
  src/components/ManageResume/EducationDetail.tsx
  src/components/ManageResume/WorkExperienceDetail.tsx
  src/components/PostApply/PostApplyResume.tsx
  src/components/PostDetail/PostDetailContent.tsx
  src/components/PostDetail/PostDetailTitle.tsx
  src/components/Profile/LevelSection.tsx
  src/components/Profile/LicenseCard.tsx
  src/components/Profile/ProfileCard.tsx
  src/components/Profile/ProfileHeader.tsx
  src/components/Signin/SigninInputSection.tsx
  src/components/Signup/SignupInput.tsx
  src/components/WorkExperience/WorkExperiencePatch.tsx
  src/components/WorkExperience/WorkExperiencePost.tsx
  src/index.css
  src/pages/ChatBot/ChatBotPage.tsx
  src/pages/Employer/Profile/EmployerProfilePage.tsx
  src/pages/LanguageSetting/LanguageSettingPage.tsx
  src/pages/ManageResumePage/ManageResumePage.tsx
  src/pages/Profile/ProfilePage.tsx
  src/pages/ScrappedJobPosts/ScrappedJobPostsPage.tsx
  src/pages/Signin/ResetPasswordPage.tsx
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&CSS

#203 [Fix/199] BottomSheet가 화면이 로드되는 동시에 안나타나는 오류
  src/components/Common/BottomSheetLayout.tsx
  src/hooks/useBottomSheet.ts
Labels: 🐞 BugFix

#205 Merge to Main
  .gitignore
  src/components/Application/ApplicationCard.tsx
  src/components/ApplicationDetail/ApplicationDetailInfo.tsx
  src/components/ApplicationDetail/ApplicationDetailStepBarLayout.tsx
  src/components/ApplicationDetail/ContactCoordinatorModal.tsx
  src/components/ApplicationDetail/ContactRecruiterModal.tsx
  src/components/Common/BottomSheetLayout.tsx
  src/components/Common/JobPostingCard.tsx
  src/components/Common/LoginBottomSheet.tsx
  src/components/Common/SearchSortDropdown.tsx
  src/components/Common/SubHeader.tsx
  src/components/Document/DocumentCard.tsx
  src/components/Document/write/InfoAlert.tsx
  src/components/Employer/ApplicantDetail/EmployerApplicantContactBottomSheet.tsx
  src/components/Employer/ApplicantDetail/EmployerApplicantDetailCard.tsx
  src/components/Employer/ApplicantDocumentsDetail/DocumentCardDispenserEmployer.tsx
  src/components/Employer/ApplicantList/EmployerApplicantCard.tsx
  src/components/Employer/ApplicantList/EmployerApplicantListTitle.tsx
  src/components/Employer/Post/EmployerPostCard.tsx
  src/components/Employer/Profile/EmployerProfileCard.tsx
  src/components/Home/HomeApplicationCard.tsx
  src/components/Home/HomeJobPostingList.tsx
  src/components/Home/HomePostCard.tsx
  src/components/Home/HomeRecommendPost.tsx
  src/components/Home/HomeRecommendPostCard.tsx
  src/components/Introduction/IntroductionInput.tsx
  src/components/Language/LanguageCard.tsx
  src/components/ManageResume/EducationDetail.tsx
  src/components/ManageResume/WorkExperienceDetail.tsx
  src/components/PostApply/PostApplyResume.tsx
  src/components/PostDetail/PostDetailContent.tsx
  src/components/PostDetail/PostDetailTitle.tsx
  src/components/Profile/LevelSection.tsx
  src/components/Profile/LicenseCard.tsx
  src/components/Profile/ProfileCard.tsx
  src/components/Profile/ProfileHeader.tsx
  src/components/Signin/SigninInputSection.tsx
  src/components/Signup/SignupInput.tsx
  src/components/WorkExperience/WorkExperiencePatch.tsx
  src/components/WorkExperience/WorkExperiencePost.tsx
  src/hooks/useBottomSheet.ts
  src/index.css
  src/pages/ChatBot/ChatBotPage.tsx
  src/pages/Employer/Profile/EmployerProfilePage.tsx
  src/pages/LanguageSetting/LanguageSettingPage.tsx
  src/pages/ManageResumePage/ManageResumePage.tsx
  src/pages/Profile/ProfilePage.tsx
  src/pages/ScrappedJobPosts/ScrappedJobPostsPage.tsx
  src/pages/Signin/ResetPasswordPage.tsx
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&CSS

#204 [Feature/197] 회원가입, 로그인 리뉴얼 관련 QA
  package.json
  pnpm-lock.yaml
  src/components/Document/write/EmployeeInfoSection.tsx
  src/components/Document/write/EmployerInfoSection.tsx
  src/components/Document/write/IntegratedApplicationPreview.tsx
  src/components/Employer/EditProfile/EmployerEditInputSection.tsx
  src/components/Employer/PostCreate/Step1.tsx
  src/components/Employer/PostCreate/Step2.tsx
  src/components/Employer/Signup/AgreeModalInner.tsx
  src/components/Employer/Signup/InformationInputSection.tsx
  src/components/Employer/WriteDocument/EmployeeInfoSectionKOR.tsx
  src/components/Information/AddressStep.tsx
  src/components/Information/InformationStep.tsx
  src/components/Signin/SigninInputSection.tsx
  src/components/Signup/SignupInput.tsx
  src/hooks/api/useAddressSearch.ts
  src/hooks/api/useAuth.ts
  src/hooks/useDebounce.ts
  src/pages/Employer/EditProfile/EmployerEditProfilePage.tsx
  src/pages/Employer/Post/EmployerCreatePostPage.tsx
  src/pages/Employer/signup/EmployerSignupInfoPage.tsx
  src/pages/Information/InformationPage.tsx
  src/types/api/auth.ts
  src/types/api/document.ts
  src/types/api/employ.ts
  src/types/api/profile.ts
  src/types/api/users.ts
  src/types/postCreate/postCreate.ts
  src/utils/document.ts
  src/utils/employerProfile.ts
  src/utils/map.tsx
  src/utils/signup.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&CSS, 📭 API

#207 [Fix] - 로그인회원가입리뉴얼 #197
  src/components/Common/Input.tsx
  src/components/Profile/Password/CurrentPasswordStep.tsx
  src/components/Profile/Password/NewPasswordStep.tsx
  src/components/Signin/SigninInputSection.tsx
  src/components/Signup/EmailInput.tsx
  src/components/Signup/SignupInput.tsx
  src/pages/Employer/Post/EmployerEditPostPage.tsx
  src/pages/Signin/ResetPasswordPage.tsx
Labels: 🐞 BugFix
