Repository Team-inglo/Giggle-Web, pull requests merged in 2025-05, with the labels that each got.

#333 [Feat/319] - 카카오맵 defer 적용 및 검색 필터 선택 시 카테고리별로 렌더링 최적화
  index.html
  src/components/PostSearchFilter/PostSearchFilterArea.tsx
  src/components/PostSearchFilter/PostSearchFilterAreaInput.tsx
  src/components/PostSearchFilter/PostSearchFilterButtons.tsx
  src/components/PostSearchFilter/PostSearchFilterList.tsx
  src/pages/PostSearch/PostSearchFilterPage.tsx
Labels: ✨ Feature

#342 [fix/319] react-kakao-maps-sdk에 autoload=false 적용하기
  index.html
Labels: 🐞 BugFix

#340 Feature/339 자기소개 필드 분리 title content
  src/api/resumes.ts
  src/components/Common/Header/BaseHeader.tsx
  src/components/Common/Input.tsx
  src/components/Common/PageTitle.tsx
  src/components/Introduction/IntroductionInput.tsx
  src/components/WorkExperience/InputLayout.tsx
  src/index.css
  src/pages/Introduction/IntroductionPage.tsx
  src/types/api/resumes.ts
  tailwind.config.js
Labels: ✨ Feature, 🎨 Html&CSS, 📭 API

#346 [feature/341] - 희망 근로 조건 필드 추가
  src/api/resumes.ts
  src/components/Common/Divider.tsx
  src/components/Common/RegionSelect.tsx
  src/components/PostSearchFilter/PostSearchFilterArea.tsx
  src/components/WorkPreference/WorkPreferenceAreaSelect.tsx
  src/components/WorkPreference/WorkPreferenceIndustrySelect.tsx
  src/components/WorkPreference/WorkPreferenceJobTypeSelect.tsx
  src/constants/post.ts
  src/hooks/api/useResume.ts
  src/pages/Resume/IntroductionPage.tsx
  src/pages/Resume/PostLanguagePage.tsx
  src/pages/Resume/ScrappedJobPostsPage.tsx
  src/pages/Resume/SetEducation/PatchEducationPage.tsx
  src/pages/Resume/SetEducation/PostEducationPage.tsx
  src/pages/Resume/SetWorkExperience/PatchWorkExperiencePage.tsx
  src/pages/Resume/SetWorkExperience/PostWorkExperiencePage.tsx
  src/pages/Resume/WorkPreferencePage.tsx
  src/router.tsx
  src/types/api/resumes.ts
  src/types/postApply/resumeDetailItem.ts
  src/types/postCreate/postCreate.ts
  src/utils/editResume.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&CSS, 📭 API

#349 Feature/348 이력서 페이지 변경점 적용
  src/api/auth.ts
  src/api/index.ts
  src/api/resumes.ts
  src/components/Common/InfoCardLayout.tsx
  src/components/Language/LanguageCard.tsx
  src/components/ManageResume/EducationDetail.tsx
  src/components/ManageResume/InfoCard.tsx
  src/components/ManageResume/IntroductionDetail.tsx
  src/components/ManageResume/LanguageManageDetail.tsx
  src/components/ManageResume/MypageCard.tsx
  src/components/ManageResume/ResumeEditSection.tsx
  src/components/ManageResume/ResumeProfileCard.tsx
  src/components/ManageResume/WorkExperienceDetail.tsx
  src/components/ManageResume/WorkPreferenceDetail.tsx
  src/components/PostApply/PostApplyResume.tsx
  src/constants/manageResume.ts
  src/hooks/api/useResume.ts
  src/pages/ManageResumePage/EditResumePage.tsx
  src/pages/ManageResumePage/ManageResumePage.tsx
  src/pages/Resume/IntroductionPage.tsx
  src/pages/Resume/PostLanguagePage.tsx
  src/pages/Resume/SetWorkExperience/PatchWorkExperiencePage.tsx
  src/pages/Resume/WorkPreferencePage.tsx
  src/router.tsx
  src/types/postApply/resumeDetailItem.ts
  src/utils/editResume.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&CSS, 📭 API

#352 Feature/351 App Bar 스펙 수정
  src/assets/icons/Home/SearchIcon.svg
  src/components/Home/HomeHeader.tsx
Labels: ✨ Feature, 🎨 Html&CSS

#355 refactor: :recycle: SearchIcon 삭제
  src/assets/icons/SearchIcon.svg
  src/components/Home/HomeHeader.tsx
Labels: 🎨 Html&CSS

#350 [Feat/344] 공고 카드 디자인 리뉴얼 및 커리어 검색 및 상세 조회 기능 구현
  src/api/career.ts
  src/assets/icons/BookmarkCheckedIcon.svg
  src/assets/icons/BookmarkIcon.svg
  src/assets/icons/CalendarIcon.svg
  src/assets/icons/FilterIcon.svg
  src/assets/icons/GlobalIcon.svg
  src/assets/icons/MoneyIcon.svg
  src/assets/icons/Post/CompanyInformationIcon.svg
  src/assets/icons/Post/DetailedOverviewIcon.svg
  src/assets/icons/Post/RecruitmentConditionsIcon.svg
  src/assets/icons/Post/WorkingConditionsIcon.svg
  src/assets/icons/Post/WorkplaceInformationIcon.svg
  src/components/Common/Header/TextFieldHeader.tsx
  src/components/Common/JobPostingCard.tsx
  src/components/Common/SearchSortDropdown.tsx
  src/components/Home/HomePostCard.tsx
  src/components/PostDetail/CareerDetailContent.tsx
  src/components/PostDetail/PostDetailCompanyImageList.tsx
  src/components/PostDetail/PostDetailContent.tsx
  src/components/PostDetail/PostDetailContentMenuBar.tsx
  src/components/PostSearch/CareerCardList.tsx
  src/components/PostSearch/CareerSearchSection.tsx
  src/components/PostSearch/PostCardList.tsx
  src/components/PostSearch/PostSearchFilterList.tsx
  src/components/PostSearch/PostSearchSection.tsx
  src/constants/postDetail.ts
  src/constants/postSearch.ts
  src/constants/translation.ts
  src/hooks/api/useCareer.ts
  src/hooks/usePostSearch.ts
  src/pages/ApplicationDetail/ApplicationDetailPage.tsx
  src/pages/Employer/ApplicantList/EmployerApplicantListPage.tsx
  src/pages/Employer/PostDetail/EmployerPostDetailPage.tsx
  src/pages/PostDetail/CareerDetailPage.tsx
  src/pages/PostDetail/PostDetailPage.tsx
  src/pages/PostSearch/PostSearchFilterPage.tsx
  src/pages/PostSearch/PostSearchPage.tsx
  src/pages/Resume/ScrappedJobPostsPage.tsx
  src/router.tsx
  src/types/api/career.ts
  src/utils/application.ts
  src/utils/formatSearchFilter.ts
  src/utils/post.ts
Labels: ✨ Feature, 🎨 Html&CSS

#358 [fix/343] 마감된 공고인 경우 closed로 표기
  src/components/Common/JobPostingCard.tsx
  src/constants/translation.ts
Labels: 🐞 BugFix, ✨ Feature

#360 fix/359 - 근무 희망 조건 업직종 enum 에러
  src/components/WorkPreference/WorkPreferenceIndustrySelect.tsx
  src/constants/post.ts
  src/types/postCreate/postCreate.ts
  src/utils/editResume.ts
Labels: 🐞 BugFix, 🎨 Html&CSS, 📭 API

#361 Merge to Main
  src/components/Common/JobPostingCard.tsx
  src/components/WorkPreference/WorkPreferenceIndustrySelect.tsx
  src/constants/post.ts
  src/constants/translation.ts
  src/types/postCreate/postCreate.ts
  src/utils/editResume.ts
Labels: 🐰 no-rabbit-zone

#365 [Task/363] - 유닛 테스트 환경 구축
  .github/workflows/jira.yml
  .github/workflows/test.yml
  .gitignore
  README.md
  package.json
  pnpm-lock.yaml
  src/__tests__/mocks/talent.ts
  src/__tests__/setup.ts
  src/__tests__/utils/api-mocks.ts
  src/__tests__/utils/test-utils.tsx
  src/components/TestExample/Button.test.tsx
  src/components/TestExample/Button.tsx
  tsconfig.app.json
  vite.config.ts
Labels: ⚙️ Setting, ✅ Test
