Repository Team-inglo/Giggle-Web, pull requests merged in 2025-04, with the labels that each got.

#292 [Fix/288] 생년월일 입력을 받는 모든 date picker → input field(YYYY-MM-DD)로 변경
  src/components/Common/Dropdown.tsx
  src/components/Employer/PostCreate/Step2.tsx
  src/components/Employer/WriteDocument/EmployerLaborContractForm.tsx
  src/components/Information/InformationStep.tsx
  src/components/Profile/Password/CurrentPasswordStep.tsx
  src/components/SetEducation/EducationPatch.tsx
  src/components/SetEducation/EducationPost.tsx
  src/components/WorkExperience/WorkExperiencePatch.tsx
  src/components/WorkExperience/WorkExperiencePost.tsx
  src/components/WriteDocuments/IntegratedApplicationWriteForm.tsx
  src/pages/EditProfile/EditProfilePage.tsx
  src/pages/Profile/ChangePasswordPage.tsx
  src/utils/information.ts
Labels: 🐞 BugFix

#296 [Fix/295] - 로그인 후 fcm 토큰 등록, 푸시 메시지 전송
  src/api/auth.ts
  src/components/Common/ReactNativeMessageListener.tsx
  src/hooks/api/useAuth.ts
  src/pages/Information/InformationPage.tsx
  src/types/api/employ.ts
Labels: 🐞 BugFix, 📭 API

#300 [Fearue/298] - 앱 실행 시 버전 체크
  src/api/version.ts
  src/components/Common/ReactNativeMessageListener.tsx
  src/hooks/api/useVersion.ts
  src/types/api/version.ts
Labels: ✨ Feature, 📭 API

#301 [Fix/299] - 앱 내 외부 웹사이트 이동 시 페이지 이동 불가 현상
  src/components/ApplicationDetail/ContactCoordinatorModal.tsx
  src/components/ApplicationDetail/ContactHikoreaBottomSheet.tsx
  src/pages/ApplicationDetail/ApplicationDetailSchoolPage.tsx
  src/utils/application.ts
Labels: 🐞 BugFix, ✨ Feature

#305 [Fix/293] 알람, 공고 검색, 서류신청관리 페이지 디자인 QA
  src/assets/icons/ApplicationDetail/MessageIcon.svg
  src/assets/icons/Home/MessageIcon.svg
  src/assets/icons/PostSearch/RegionCheckIcon.svg
  src/components/Alarm/AlarmCard.tsx
  src/components/Alarm/AlarmCardList.tsx
  src/components/ApplicationDetail/ApplicationDetailStep7.tsx
  src/components/ApplicationDetail/ApplicationDetailStepEtc.tsx
  src/components/ApplicationDetail/ApplicationDetailSteps.tsx
  src/components/Employer/ApplicantDetail/EmployerApplicantDetailButton.tsx
  src/components/Home/HomeRecommendPost.tsx
  src/components/Home/HomeRecommendPostCard.tsx
  src/components/PostSearchFilter/PostSearchFilterArea.tsx
  src/components/PostSearchFilter/PostSearchFilterAreaSelect.tsx
  src/components/PostSearchFilter/PostSearchFilterBottomSheet.tsx
  src/constants/regionData.ts
  src/constants/translation.ts
  src/hooks/api/useAlarm.ts
  src/pages/Alarm/AlarmPage.tsx
  src/pages/ApplicationDetail/ApplicationDetailPage.tsx
  src/pages/Employer/ApplicantDetail/EmployerApplicantDetailPage.tsx
  src/types/api/application.ts
  src/utils/post.ts
Labels: 🐞 BugFix

#306 [Fix/304] 문서 수정 작성 후 뒤로 가기 시 작성 수정 UI로 이동
  src/components/ApplicationDetail/ContactHikoreaBottomSheet.tsx
  src/components/Document/DocumentCard.tsx
  src/components/Document/DocumentCardList.tsx
  src/components/Document/MakeDocumentButton.tsx
  src/components/Employer/ApplicantDetail/EmployerApplicantContactBottomSheet.tsx
  src/components/Employer/ApplicantDetail/EmployerApplicantDetailCard.tsx
  src/components/Employer/ApplicantDocumentsDetail/DocumentCardDispenserEmployer.tsx
  src/components/Employer/WriteDocument/EmployerLaborContractForm.tsx
  src/components/Employer/WriteDocument/EmployerPartTimePermitForm.tsx
  src/components/WriteDocuments/DocumentFormDispenser.tsx
  src/components/WriteDocuments/IntegratedApplicationWriteForm.tsx
  src/components/WriteDocuments/LaborContractWriteForm.tsx
  src/components/WriteDocuments/PartTimePermitWriteForm.tsx
  src/hooks/api/useApplication.ts
  src/hooks/api/useAuth.ts
  src/hooks/api/useDocument.ts
  src/hooks/api/usePost.ts
  src/hooks/api/useProfile.ts
  src/hooks/api/useResume.ts
  src/hooks/api/useSetting.ts
  src/pages/ApplicationDetail/ApplicationDetailPage.tsx
  src/pages/ApplicationDocuments/ApplicationDocumentsPage.tsx
  src/pages/Employer/Post/EmployerCreatePostPage.tsx
  src/pages/Employer/Post/EmployerEditPostPage.tsx
  src/pages/Employer/WriteDocuments/ApplicantDocumentsDetailPage.tsx
  src/pages/Employer/WriteDocuments/EmployerWriteDocumentsPage.tsx
  src/pages/WriteDocuments/DocumentPreviewPage.tsx
  src/pages/WriteDocuments/RequestModifyPage.tsx
  src/pages/WriteDocuments/WriteDocumentsPage.tsx
  src/router.tsx
  src/store/url.ts
  src/utils/application.ts
  src/utils/clearAllStore.ts
Labels: ✨ Feature

#307 [Fix/276]-면접 완료 후 서류 작성 알림 클릭 시 빈 화면 에러
  src/components/Common/JobPostingCard.tsx
  src/hooks/api/useDocument.ts
Labels: 🐞 BugFix, 📭 API

#308 🐛 fix: 학교 담당자 연결, 하이코리아 처리 결과 등록하기 단계 스마트 네비게이션 적용 #304
  src/hooks/api/useApplication.ts
  src/pages/ApplicationResult/ApplicationResultPage.tsx
Labels: 🐞 BugFix

#313 [Fix/312] 이메일 전송 시에 스팸함 안내 문구 추가하기
  src/components/Signup/SignupInput.tsx
  src/constants/translation.ts
  src/pages/Signin/ResetPasswordPage.tsx
Labels: 🐞 BugFix

#316 Update README.md
  README.md
Labels: 📄 Docs

#318 [Fix/317] - 마이페이지 디자인 변경 적용
  src/assets/icons/Profile/ToggleBar.svg
  src/components/Employer/Profile/EmployerJobInfo.tsx
  src/components/Employer/Profile/EmployerProfileCard.tsx
  src/components/Employer/Profile/EmployerProfileMenu.tsx
  src/components/Employer/Profile/EmployerProfileMenuList.tsx
  src/components/Profile/ApplicationStatus.tsx
  src/components/Profile/ProfileCard.tsx
  src/components/Profile/ProfileMenu.tsx
  src/components/Profile/ProfileMenuList.tsx
  src/constants/profile.ts
  src/pages/Employer/Profile/EmployerProfilePage.tsx
  src/pages/Profile/AboutPage.tsx
  src/pages/Profile/AccountPage.tsx
  src/pages/Profile/ProfilePage.tsx
  tailwind.config.js
Labels: 🎨 Html&CSS

#320 Merge To main
  src/assets/icons/Profile/ToggleBar.svg
  src/components/Employer/Profile/EmployerJobInfo.tsx
  src/components/Employer/Profile/EmployerProfileCard.tsx
  src/components/Employer/Profile/EmployerProfileMenu.tsx
  src/components/Employer/Profile/EmployerProfileMenuList.tsx
  src/components/Profile/ApplicationStatus.tsx
  src/components/Profile/ProfileCard.tsx
  src/components/Profile/ProfileMenu.tsx
  src/components/Profile/ProfileMenuList.tsx
  src/constants/profile.ts
  src/pages/Employer/Profile/EmployerProfilePage.tsx
  src/pages/Profile/AboutPage.tsx
  src/pages/Profile/AccountPage.tsx
  src/pages/Profile/ProfilePage.tsx
  tailwind.config.js
Labels: 🎨 Html&CSS

#324 Fix/323 공고 생성 후 뒤로가기 시 작성 페이지로 복귀하는 문제
  .coderabbit.yml
  src/pages/Employer/Post/EmployerCreatePostPage.tsx
Labels: 🐞 BugFix, 🐰 no-rabbit-zone

#325 [Fix/322] 이미 지원 완료한 공고 지원 시에 하단 모달 2개 출현하는 오류
  src/App.tsx
  src/components/PostApply/PostApplyButton.tsx
  src/hooks/api/useApplication.ts
  src/store/error.ts
Labels: 🐞 BugFix

#326 Merge to Main
  .coderabbit.yml
  src/App.tsx
  src/components/PostApply/PostApplyButton.tsx
  src/hooks/api/useApplication.ts
  src/pages/Employer/Post/EmployerCreatePostPage.tsx
  src/store/error.ts
Labels: 🐞 BugFix, 🐰 no-rabbit-zone

#328 🐛 fix: 회원가입 중 이름 입력 시 공백 허용 및 공백 길이 자동 조절 #327
  src/components/Information/InformationStep.tsx
  src/utils/information.ts
Labels: 🐞 BugFix, 🎨 Html&CSS

#329 Merge To main
  src/components/Information/InformationStep.tsx
  src/utils/information.ts
Labels: 🐞 BugFix, 🎨 Html&CSS

#332 🐛 fix: 유학생의 문서 생성 후 제출 전 고용주에게 동일한 ui 제공 #331
  src/pages/Employer/WriteDocuments/ApplicantDocumentsDetailPage.tsx
Labels: 🐞 BugFix
